import { Knex } from 'knex'

export async function seed(knex: Knex): Promise<void> {
  await knex('questions').del()

  await knex('questions').insert([
    // A1 — 中医基础理论
    { id: 'q-a1-zhongji-001', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'zhongji', chapter_id: 'ch-zhongji-02', section_id: '', knowledge_point_ids_json: '[]', difficulty: 2, exam_years_json: '[]', question_stem: '阴阳学说中，"阴胜则阳病，阳胜则阴病"说明了阴阳之间的哪种关系？', options_json: '[{"key":"A","text":"阴阳对立制约"},{"key":"B","text":"阴阳互根互用"},{"key":"C","text":"阴阳消长平衡"},{"key":"D","text":"阴阳相互转化"},{"key":"E","text":"阴阳交感与互藏"}]', shared_options_json: null, correct_answer: 'A', explanation: '"阴胜则阳病，阳胜则阴病"出自《素问·阴阳应象大论》，意指阴邪偏盛则损伤阳气而致阳病，阳邪偏盛则损伤阴液而致阴病。这体现了阴阳之间相互制约的关系。', tags_json: '["阴阳学说","高频"]', order_in_group: 0 },
    { id: 'q-a1-zhongji-002', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'zhongji', chapter_id: 'ch-zhongji-02', section_id: '', knowledge_point_ids_json: '[]', difficulty: 2, exam_years_json: '[]', question_stem: '所谓"孤阴不生，独阳不长"体现了阴阳的哪种关系？', options_json: '[{"key":"A","text":"阴阳对立制约"},{"key":"B","text":"阴阳互根互用"},{"key":"C","text":"阴阳消长平衡"},{"key":"D","text":"阴阳相互转化"},{"key":"E","text":"阴阳交感与互藏"}]', shared_options_json: null, correct_answer: 'B', explanation: '"孤阴不生，独阳不长"说明阴阳双方相互依存、互为根本的关系。阴和阳任何一方都不能脱离另一方而单独存在。', tags_json: '["阴阳学说","高频"]', order_in_group: 0 },
    { id: 'q-a1-zhongji-003', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'zhongji', chapter_id: 'ch-zhongji-03', section_id: '', knowledge_point_ids_json: '[]', difficulty: 2, exam_years_json: '[]', question_stem: '五行学说中，"木"的特性是：', options_json: '[{"key":"A","text":"曲直"},{"key":"B","text":"炎上"},{"key":"C","text":"稼穑"},{"key":"D","text":"从革"},{"key":"E","text":"润下"}]', shared_options_json: null, correct_answer: 'A', explanation: '五行特性出自《尚书·洪范》："木曰曲直"，指树木具有能屈能伸、向上向外生长的特性。', tags_json: '["五行学说","基础"]', order_in_group: 0 },
    { id: 'q-a1-zhongji-004', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'zhongji', chapter_id: 'ch-zhongji-04', section_id: '', knowledge_point_ids_json: '[]', difficulty: 3, exam_years_json: '[]', question_stem: '被称为"后天之本"的脏是：', options_json: '[{"key":"A","text":"心"},{"key":"B","text":"肝"},{"key":"C","text":"脾"},{"key":"D","text":"肺"},{"key":"E","text":"肾"}]', shared_options_json: null, correct_answer: 'C', explanation: '脾主运化，为气血生化之源，故称"后天之本"。肾藏精，为"先天之本"。', tags_json: '["藏象","藏象学说"]', order_in_group: 0 },
    { id: 'q-a1-zhongji-005', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'zhongji', chapter_id: 'ch-zhongji-08', section_id: '', knowledge_point_ids_json: '[]', difficulty: 2, exam_years_json: '[]', question_stem: '六淫中，其性"凝滞"的邪气是：', options_json: '[{"key":"A","text":"风邪"},{"key":"B","text":"寒邪"},{"key":"C","text":"湿邪"},{"key":"D","text":"燥邪"},{"key":"E","text":"火邪"}]', shared_options_json: null, correct_answer: 'B', explanation: '寒为阴邪，其性凝滞——凝结、阻滞不通之意。湿邪重浊黏滞，风邪善行数变，燥邪干涩，火邪炎上。', tags_json: '["病因","六淫"]', order_in_group: 0 },
    // A2 — 中医诊断学
    { id: 'q-a2-zhenjuan-001', question_type: 'A2', is_group_root: 0, group_id: null, subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', section_id: '', knowledge_point_ids_json: '[]', difficulty: 3, exam_years_json: '[]', question_stem: '患者面色淡白无华，唇舌色淡，头晕眼花，心悸失眠，手足麻木，妇女月经量少色淡、愆期，舌淡苔白，脉细无力。其证候属于：', options_json: '[{"key":"A","text":"气虚证"},{"key":"B","text":"血虚证"},{"key":"C","text":"阴虚证"},{"key":"D","text":"阳虚证"},{"key":"E","text":"气血两虚证"}]', shared_options_json: null, correct_answer: 'B', explanation: '面色、唇舌淡白无华+头晕眼花+心悸失眠+手足麻木+月经量少色淡+脉细无力，均为血虚失于濡养之象。', tags_json: '["八纲辨证","气血辨证"]', order_in_group: 0 },
    { id: 'q-a2-zhenjuan-002', question_type: 'A2', is_group_root: 0, group_id: null, subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', section_id: '', knowledge_point_ids_json: '[]', difficulty: 3, exam_years_json: '[]', question_stem: '患者腹部胀满疼痛，按之痛甚，大便秘结不通，舌苔黄厚而燥，脉沉实有力。其病性属：', options_json: '[{"key":"A","text":"表寒证"},{"key":"B","text":"里虚证"},{"key":"C","text":"里实证"},{"key":"D","text":"真热假寒证"},{"key":"E","text":"真寒假热证"}]', shared_options_json: null, correct_answer: 'C', explanation: '腹部胀满疼痛+按之痛甚+大便秘结不通+苔黄厚燥+脉沉实有力，均为里实证表现。无虚象，无恶寒发热。', tags_json: '["八纲辨证","实证"]', order_in_group: 0 },
    { id: 'q-a2-zhenjuan-003', question_type: 'A2', is_group_root: 0, group_id: null, subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-06', section_id: '', knowledge_point_ids_json: '[]', difficulty: 4, exam_years_json: '[]', question_stem: '患者咳嗽痰少而黏，不易咯出，或痰中带血，口燥咽干，声音嘶哑，形体消瘦，午后潮热，五心烦热，盗汗，颧红，舌红少苔，脉细数。其辨证为：', options_json: '[{"key":"A","text":"风寒犯肺证"},{"key":"B","text":"风热犯肺证"},{"key":"C","text":"痰热壅肺证"},{"key":"D","text":"肺阴虚证"},{"key":"E","text":"肺气虚证"}]', shared_options_json: null, correct_answer: 'D', explanation: '咳嗽痰少而黏+痰中带血+口燥咽干+午后潮热+五心烦热+盗汗+颧红+舌红少苔+脉细数，均为肺阴虚证典型表现。', tags_json: '["脏腑辨证","肺病辨证"]', order_in_group: 0 },
    // B1 — 中药学
    { id: 'q-b1-zhongyao-grp-001', question_type: 'B1', is_group_root: 1, group_id: null, subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-01', section_id: '', knowledge_point_ids_json: '[]', difficulty: 3, exam_years_json: '[]', question_stem: '', options_json: '[]', shared_options_json: '[{"key":"A","text":"辛温解表药"},{"key":"B","text":"辛凉解表药"},{"key":"C","text":"清热泻火药"},{"key":"D","text":"清热燥湿药"},{"key":"E","text":"清热凉血药"}]', correct_answer: '', explanation: '解表药与清热药的分类。麻黄——辛温解表药；柴胡——辛凉解表药。', tags_json: '["中药分类","解表药"]', order_in_group: 0 },
    { id: 'q-b1-zhongyao-sub-001', question_type: 'B1', is_group_root: 0, group_id: 'q-b1-zhongyao-grp-001', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-01', section_id: '', knowledge_point_ids_json: '[]', difficulty: 3, exam_years_json: '[]', question_stem: '麻黄按功效分类属于：', options_json: '[]', shared_options_json: null, correct_answer: 'A', explanation: '麻黄性辛、微苦、温，归肺、膀胱经，为发汗解表之峻品，属**辛温解表药**。', tags_json: '["中药分类","解表药"]', order_in_group: 1 },
    { id: 'q-b1-zhongyao-sub-002', question_type: 'B1', is_group_root: 0, group_id: 'q-b1-zhongyao-grp-001', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-01', section_id: '', knowledge_point_ids_json: '[]', difficulty: 3, exam_years_json: '[]', question_stem: '柴胡按功效分类属于：', options_json: '[]', shared_options_json: null, correct_answer: 'B', explanation: '柴胡性辛、苦、微寒，归肝、胆、肺经，属**辛凉解表药**，为少阳经引经药。', tags_json: '["中药分类","解表药"]', order_in_group: 2 },
    // A1 — 方剂学
    { id: 'q-a1-fangji-001', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'fangji', chapter_id: 'ch-fangji-02', section_id: '', knowledge_point_ids_json: '[]', difficulty: 2, exam_years_json: '[]', question_stem: '麻黄汤的组成药物是：', options_json: '[{"key":"A","text":"麻黄、桂枝、杏仁、甘草"},{"key":"B","text":"麻黄、桂枝、芍药、甘草"},{"key":"C","text":"麻黄、细辛、干姜、甘草"},{"key":"D","text":"麻黄、石膏、杏仁、甘草"},{"key":"E","text":"麻黄、附子、细辛、甘草"}]', shared_options_json: null, correct_answer: 'A', explanation: '麻黄汤出自《伤寒论》，由麻黄、桂枝、杏仁、甘草（炙）组成。D为麻杏石甘汤。', tags_json: '["方剂组成","解表剂"]', order_in_group: 0 },
    { id: 'q-a1-fangji-002', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'fangji', chapter_id: 'ch-fangji-01', section_id: '', knowledge_point_ids_json: '[]', difficulty: 2, exam_years_json: '[]', question_stem: '方剂组成原则中，"君药"的含义是：', options_json: '[{"key":"A","text":"方中用量最大的药物"},{"key":"B","text":"针对主病或主证起主要治疗作用的药物"},{"key":"C","text":"方中价格最贵的药物"},{"key":"D","text":"方中毒性最大的药物"},{"key":"E","text":"方中起调和诸药作用的药物"}]', shared_options_json: null, correct_answer: 'B', explanation: '君药针对主病或主证起主要治疗作用，是不可缺少的核心药物。调和诸药为使药。', tags_json: '["方剂学基础","君臣佐使"]', order_in_group: 0 },
    { id: 'q-a1-fangji-003', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'fangji', chapter_id: 'ch-fangji-03', section_id: '', knowledge_point_ids_json: '[]', difficulty: 3, exam_years_json: '[]', question_stem: '桂枝汤的主治病证是：', options_json: '[{"key":"A","text":"外感风寒表实证"},{"key":"B","text":"外感风寒表虚证"},{"key":"C","text":"外感风热表证"},{"key":"D","text":"外感风寒湿表证"},{"key":"E","text":"外感风寒夹湿证"}]', shared_options_json: null, correct_answer: 'B', explanation: '桂枝汤解肌发表、调和营卫，主治外感风寒表虚证（发热恶风汗出脉浮缓）。麻黄汤主治表实证（无汗）。', tags_json: '["解表剂","桂枝汤"]', order_in_group: 0 },
    // A1 — 针灸学
    { id: 'q-a1-zhenjiu-001', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'zhenjiu', chapter_id: 'ch-zhenjiu-02', section_id: '', knowledge_point_ids_json: '[]', difficulty: 2, exam_years_json: '[]', question_stem: '十二经脉中，被称为"阳脉之海"的是：', options_json: '[{"key":"A","text":"督脉"},{"key":"B","text":"任脉"},{"key":"C","text":"冲脉"},{"key":"D","text":"带脉"},{"key":"E","text":"足阳明胃经"}]', shared_options_json: null, correct_answer: 'A', explanation: '督脉行于背部正中，总督一身之阳经，称"阳脉之海"。任脉称"阴脉之海"。冲脉为"十二经脉之海"。', tags_json: '["经络","奇经八脉"]', order_in_group: 0 },
    { id: 'q-a1-zhenjiu-002', question_type: 'A1', is_group_root: 0, group_id: null, subject_id: 'zhenjiu', chapter_id: 'ch-zhenjiu-03', section_id: '', knowledge_point_ids_json: '[]', difficulty: 2, exam_years_json: '[]', question_stem: '合谷穴的定位是：', options_json: '[{"key":"A","text":"在手背，第1、2掌骨间，当第2掌骨桡侧的中点处"},{"key":"B","text":"在手背，第2、3掌骨间"},{"key":"C","text":"在手掌，第1、2掌骨间"},{"key":"D","text":"在前臂，腕横纹上2寸"},{"key":"E","text":"在拇指末节桡侧，距指甲角0.1寸"}]', shared_options_json: null, correct_answer: 'A', explanation: '合谷穴为手阳明大肠经原穴。D为内关穴，E为少商穴。', tags_json: '["腧穴定位","手阳明大肠经"]', order_in_group: 0 },
  ])

  console.log('[Seed 003] 16道题目已导入')
}
