import { Knex } from 'knex'

export async function seed(knex: Knex): Promise<void> {
  const now = Date.now()
  const cards: Array<{
    id: string; subject_id: string; chapter_id: string; knowledge_point_ids_json: string
    front_content: string; back_content: string; mnemonic: string; category: string
    tags_json: string; created_at: number; is_system: number
  }> = [

    // ================================================================
    // 中医基础理论 (15 cards) — zhongji
    // ================================================================
    { id: 'fc-zhongji3-100', subject_id: 'zhongji', chapter_id: 'ch-zhongji-04', knowledge_point_ids_json: '[]', front_content: '肺主通调水道的含义和机理是什么？', back_content: '肺通调水道即肺对水液代谢的调节作用。\n机理：\n1. 宣发——将津液向上向外布散至体表和上部\n2. 肃降——将津液向下向内输送至肾和膀胱\n3. "肺为水之上源"——上源不通则下流不畅\n\n病理：肺失宣降可导致痰饮水肿小便不利。', mnemonic: '肺→水上源→宜降调→宣发外散+肃降下达', category: 'definition', tags_json: '["藏象","肺","通调水道"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-101', subject_id: 'zhongji', chapter_id: 'ch-zhongji-08', knowledge_point_ids_json: '[]', front_content: '六淫各自的性质和致病特点总结', back_content: '风：轻扬开泄、善行数变、主动、为百病之长\n寒：阴邪伤阳、凝滞收引、澄澈清冷\n暑：炎热升散、伤津耗气、多夹湿\n湿：重浊、黏滞、趋下、伤阳阻气\n燥：干涩伤津、易伤肺\n火（热）：炎上灼津、耗气动血、生风扰神、易致疮痈', mnemonic: '风寒暑湿燥火→风动寒凝暑升湿浊燥干火炎', category: 'definition', tags_json: '["病因","六淫","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-102', subject_id: 'zhongji', chapter_id: 'ch-zhongji-08', knowledge_point_ids_json: '[]', front_content: '七情内伤的致病特点有哪些？', back_content: '1. 直接伤及五脏：怒伤肝、喜伤心、思伤脾、悲忧伤肺、惊恐伤肾\n2. 影响脏腑气机：怒则气上、喜则气缓、悲则气消、恐则气下、惊则气乱、思则气结\n3. 多发为情志病证：郁证、癫狂、不寐等\n4. 七情变化与病情密切相关：情志异常波动可使病情加重恶化', mnemonic: '七情→直接伤五脏+扰乱气机→怒上喜缓悲消恐下惊乱思结', category: 'definition', tags_json: '["病因","七情","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-103', subject_id: 'zhongji', chapter_id: 'ch-zhongji-08', knowledge_point_ids_json: '[]', front_content: '痰饮的致病特点是什么？', back_content: '痰饮为水液代谢障碍所形成的病理产物。\n痰=稠浊，饮=清稀。\n\n致病特点：\n1. 阻滞气机、阻碍气血运行\n2. 致病广泛、变化多端——"百病多由痰作祟"\n3. 病势缠绵、病程较长\n4. 易扰乱心神（痰迷心窍）\n5. 多见滑腻苔', mnemonic: '痰饮→阻气+多变+缠绵+迷心→百病痰作祟', category: 'definition', tags_json: '["病因","痰饮","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-104', subject_id: 'zhongji', chapter_id: 'ch-zhongji-08', knowledge_point_ids_json: '[]', front_content: '瘀血的致病特点和临床表现有哪些？', back_content: '瘀血为血液停滞所形成的病理产物。\n\n致病特点：\n1. 疼痛——刺痛固定不移拒按夜甚\n2. 肿块——体表青紫肿胀体内癥积坚硬\n3. 出血——血色紫暗夹有血块\n4. 面色黧黑口唇紫暗舌质紫暗有瘀斑瘀点脉涩\n5. 肌肤甲错', mnemonic: '瘀血→痛如刺、块青紫、血色暗、舌瘀斑、脉涩', category: 'definition', tags_json: '["病因","瘀血","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-105', subject_id: 'zhongji', chapter_id: 'ch-zhongji-09', knowledge_point_ids_json: '[]', front_content: '邪正盛衰与疾病转归的关系是什么？', back_content: '1. 正胜邪退：正气战胜邪气→疾病好转痊愈\n2. 邪胜正衰：邪气亢盛正气衰败→疾病恶化甚则死亡\n3. 邪正相持：正邪双方势均力敌→疾病迁延日久（慢性化）\n4. 正虚邪恋：正气已虚邪气未尽→转为慢性或后遗症\n5. 邪去正虚：邪气虽去正气大伤→恢复期', mnemonic: '五转归→正胜好+邪胜坏+相持慢+虚恋留+邪去虚', category: 'definition', tags_json: '["病机","邪正盛衰","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-106', subject_id: 'zhongji', chapter_id: 'ch-zhongji-09', knowledge_point_ids_json: '[]', front_content: '阴阳失调包括哪些类型？', back_content: '1. 阴阳偏盛（实证）：阳胜则热、阴胜则寒\n2. 阴阳偏衰（虚证）：阳虚则寒、阴虚则热\n3. 阴阳互损（阴阳两虚）：阴损及阳、阳损及阴\n4. 阴阳格拒（真假寒热）：阴盛格阳（真寒假热）、阳盛格阴（真热假寒）\n5. 阴阳亡失：亡阴（汗热黏）、亡阳（汗清稀）', mnemonic: '偏盛实+偏衰虚+互损两虚+格拒真假+亡失踪', category: 'definition', tags_json: '["病机","阴阳失调","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-107', subject_id: 'zhongji', chapter_id: 'ch-zhongji-10', knowledge_point_ids_json: '[]', front_content: '中医"治未病"理论包括哪些内容？', back_content: '1. 未病先防：\n   - 调摄精神形体（顺应自然、养性调神、锻炼身体）\n   - 药物预防及人工免疫\n   - 防止病邪侵害\n2. 既病防变：\n   - 早期诊治（"善治者治皮毛"）\n   - 防止传变（"见肝之病知肝传脾当先实脾"）', mnemonic: '未病先防+既病防变=治未病；先防调神防邪，防变早治截传', category: 'clinical', tags_json: '["防治原则","治未病","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-108', subject_id: 'zhongji', chapter_id: 'ch-zhongji-10', knowledge_point_ids_json: '[]', front_content: '正治（逆治）与反治（从治）的区别及各自包含的方法？', back_content: '正治（逆治）——药性与疾病性质相反：\n寒者热之、热者寒之、虚则补之、实则泻之\n\n反治（从治）——药性顺从疾病假象：\n热因热用（真寒假热证用热药）\n寒因寒用（真热假寒证用寒药）\n塞因塞用（真虚假实证用补药）\n通因通用（真实假虚证用通利药）', mnemonic: '正治逆其现象（寒热虚实用），反治从其假象（真假用）', category: 'clinical', tags_json: '["防治原则","正反治","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-109', subject_id: 'zhongji', chapter_id: 'ch-zhongji-10', knowledge_point_ids_json: '[]', front_content: '"三因制宜"的具体内容是什么？', back_content: '1. 因时制宜：根据时令气候制定治则（"用寒远寒用热远热"）\n2. 因地制宜：根据地理环境制定治则（西北高寒用温热东南湿热用清利）\n3. 因人制宜：根据年龄性别体质制定治则\n   - 老人多虚慎攻、小儿脏腑娇嫩慎补攻\n   - 妇女经带胎产各期治法不同\n   - 体质壮实耐攻虚弱不耐攻', mnemonic: '三因→时（四时）、地（地域）、人（年龄性别体质）', category: 'clinical', tags_json: '["防治原则","三因制宜"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-110', subject_id: 'zhongji', chapter_id: 'ch-zhongji-04', knowledge_point_ids_json: '[]', front_content: '心包的生理功能是什么？为何被称为"臣使之官"？', back_content: '心包为心的外围组织，具有保护心脏的作用。\n\n"臣使之官"：\n- 代心受邪——病邪侵犯心脏时心包先受（"心包代心受邪"）\n- 病理上：外感热病出现神昏谵语为"热入心包"\n- 治疗上：取心包经穴位治疗心病（内关治心悸心痛）', mnemonic: '心包→护心之臣→代心受邪→热入心包=神昏', category: 'definition', tags_json: '["藏象","心包"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-111', subject_id: 'zhongji', chapter_id: 'ch-zhongji-05', knowledge_point_ids_json: '[]', front_content: '精的概念、分类和功能是什么？', back_content: '概念：精是构成人体和维持生命活动的基本物质。\n\n分类：\n1. 先天之精——禀受于父母的生殖之精（藏于肾）\n2. 后天之精——脾胃运化的水谷精微（藏于五脏）\n\n功能：\n1. 繁衍生殖 2. 促进生长发育\n3. 濡养脏腑组织 4. 化生血液 5. 转化为气', mnemonic: '精→先天父母+后天水谷→繁衍生长濡养化血化气', category: 'definition', tags_json: '["精气血津液","精"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-112', subject_id: 'zhongji', chapter_id: 'ch-zhongji-09', knowledge_point_ids_json: '[]', front_content: '"气逆"的临床表现主要涉及哪些脏腑？', back_content: '气逆为气机升降失调当降不降反而逆上。\n\n主要涉及：\n1. 肺气上逆：咳嗽、气喘、胸闷\n2. 胃气上逆：恶心、呕吐、呃逆、嗳气\n3. 肝气上逆：头痛、眩晕、面红目赤、甚则呕血（肝火上炎）\n\n病机：多为实证（痰浊食积气郁等阻滞）', mnemonic: '气逆三脏→肺咳喘、胃呕呃、肝头痛眩晕', category: 'definition', tags_json: '["病机","气逆","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-113', subject_id: 'zhongji', chapter_id: 'ch-zhongji-06', knowledge_point_ids_json: '[]', front_content: '冲脉与女子月经及生殖功能的关系？', back_content: '冲脉为"十二经脉之海""血海"。\n\n与女子关系：\n1. 调节十二经脉气血→血海充盈则月经正常\n2. "冲为血海"，冲脉气血是月经的物质基础\n3. 冲脉与任脉同起于胞中→"任主胞胎冲为血海"\n4. 冲任不调为妇科病常见病机\n5. 妇科治疗常调冲任', mnemonic: '冲→血海→月经之源→调冲任=治妇科', category: 'definition', tags_json: '["经络","冲脉","妇科"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji3-114', subject_id: 'zhongji', chapter_id: 'ch-zhongji-07', knowledge_point_ids_json: '[]', front_content: '体质学说对临床治疗的指导意义是什么？', back_content: '1. 因人制宜——体质不同治疗各异（阳盛之体慎用温热）\n2. 剂量的个体化——体质壮实用药量宜大、虚弱宜小\n3. 善后调理——根据体质特点指导病后饮食起居\n4. "同病异治"——同一疾病体质不同治法不同\n5. 预防为主——根据体质预测疾病倾向及早干预', mnemonic: '体质→治疗个体化→量不同+法不同+善后不同', category: 'clinical', tags_json: '["体质","临床应用"]', created_at: now, is_system: 1 },

    // ================================================================
    // 中医诊断学 (15 cards) — zhenjuan
    // ================================================================
    { id: 'fc-zhenjuan3-100', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '五色主病（青赤黄白黑）各主什么病证？', back_content: '青：寒证、痛证、气滞、血瘀、惊风（小儿）\n赤：热证（实热—满面通红；虚热—颧红）\n黄：脾虚、湿证（萎黄—脾虚气血不足；黄疸—黄如橘皮/晦暗如烟熏）\n白：虚证（气虚血虚阳虚）、寒证、失血\n黑：肾虚、寒证、水饮、血瘀、剧痛', mnemonic: '青→寒痛瘀惊；赤→热；黄→脾虚湿；白→虚寒失血；黑→肾寒水瘀', category: 'definition', tags_json: '["望诊","五色","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-101', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '舌诊中舌色变化的临床意义有哪些？', back_content: '淡白舌：主虚证（气虚、血虚、阳虚）、寒证\n红舌：主热证（实热或虚热）\n绛舌（深红）：主热入营血或阴虚火旺\n青紫舌：主血瘀（全舌青紫=寒凝血瘀；舌有瘀斑=血瘀）\n淡紫舌：气虚血瘀\n\n舌色越红=热越重；越淡白=虚越重。', mnemonic: '舌色→淡白虚寒+红热+绛入营+紫瘀→由淡及红及紫', category: 'definition', tags_json: '["舌诊","舌色","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-102', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-04', knowledge_point_ids_json: '[]', front_content: '常见28种脉象的分类记忆法', back_content: '按脉位：浮（浮洪濡散芤革）沉（沉伏牢弱）\n按脉率：迟（迟缓涩结）数（数疾促动）\n按脉宽：大（洪大实）小（细小微）\n按脉长：长、短\n按力度：虚（虚弱微）实（实弦紧滑）\n按流利度：滑、涩\n按紧张度：弦、紧、革、濡\n按均匀度：结（缓而中止）代（止有定数）促（数而中止）', mnemonic: '浮沉迟数大小长虚滑弦代→十字诀扩展为28脉', category: 'definition', tags_json: '["脉诊","脉象分类","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-103', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-04', knowledge_point_ids_json: '[]', front_content: '虚证脉象（虚脉类）包括哪些脉象及其特征？', back_content: '虚脉：三部脉举按无力按之空虚（无力脉的总称）\n细脉：脉细如线应指明显（主气血两虚、湿证）\n微脉：极细极软若有若无（主阳衰气血大虚）\n弱脉：沉细而软（主气血两虚）\n濡脉：浮细而软（主虚证、湿证）\n短脉：首尾俱短不能满部（主气虚）', mnemonic: '虚类六脉→虚大无力+细微极弱濡浮软+短不满位', category: 'definition', tags_json: '["脉诊","虚脉","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-104', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-06', knowledge_point_ids_json: '[]', front_content: '心气虚证、心阳虚证、心阳暴脱证如何鉴别？', back_content: '心气虚：心悸怔忡+胸闷气短+自汗+活动加重（气虚象）\n心阳虚：心气虚症状+畏寒肢冷+心痛（阳虚寒象）\n心阳暴脱：心阳虚基础上+突然冷汗淋漓四肢厥冷呼吸微弱脉微欲绝（亡阳）\n\n三者渐次加重：气虚→阳虚→亡阳。', mnemonic: '心气虚→心阳虚→心阳脱：加寒加痛加脱象', category: 'clinical', tags_json: '["脏腑辨证","心病","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-105', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-06', knowledge_point_ids_json: '[]', front_content: '脾气虚证、脾阳虚证、脾虚气陷证、脾不统血证的鉴别要点？', back_content: '共同的脾气虚基础：食少腹胀便溏乏力舌淡脉弱\n\n脾气虚证：基础症状+面色萎黄\n脾阳虚证：脾气虚+畏寒肢冷腹痛喜温（阳虚寒象）\n脾虚气陷证：脾气虚+内脏下垂（脱肛子宫下垂）\n脾不统血证：脾气虚+出血（便血崩漏肌衄）', mnemonic: '脾气虚为基→加寒=脾阳虚+加陷=气陷+加血=不统血', category: 'clinical', tags_json: '["脏腑辨证","脾病","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-106', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-06', knowledge_point_ids_json: '[]', front_content: '肝气郁结证、肝火上炎证、肝阳上亢证的鉴别？', back_content: '肝气郁结：情志抑郁+胸胁胀痛走窜+脉弦（气滞为主）\n肝火上炎：头痛眩晕+面红目赤+口苦烦躁+舌红苔黄脉弦数（实火）\n肝阳上亢：上盛（眩晕头痛面红目赤脉弦）+下虚（腰膝酸软舌红少苔）（阴虚阳亢）\n\n病机演变：郁→火→亢（由实转虚为虚实夹杂）', mnemonic: '肝郁气滞→肝火实热→肝阳虚实兼→情志→火热→阴亏', category: 'clinical', tags_json: '["脏腑辨证","肝病","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-107', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-08', knowledge_point_ids_json: '[]', front_content: '六经辨证中太阳病、阳明病、少阳病、太阴病、少阴病、厥阴病的提纲证各是什么？', back_content: '太阳病：脉浮头项强痛而恶寒\n阳明病：胃家实（身热汗出口渴脉洪大）\n少阳病：口苦咽干目眩\n太阴病：腹满而吐食不下自利益甚时腹自痛\n少阴病：脉微细但欲寐\n厥阴病：消渴气上撞心心中疼热饥而不欲食', mnemonic: '太阳浮紧阳明热实少阳苦眩太阴吐利少阴微寐厥阴消渴', category: 'definition', tags_json: '["其他辨证","六经辨证","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-108', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-03', knowledge_point_ids_json: '[]', front_content: '问疼痛的鉴别要点有哪些？', back_content: '性质：胀痛=气滞；刺痛=血瘀；冷痛=寒证；灼痛=热证\n隐痛=虚证；重痛=湿阻；酸痛=湿或肾虚\n绞痛=有形实邪阻滞；空痛=气血虚或肾精亏\n走窜痛=气滞或风邪；固定痛=血瘀或寒湿\n\n部位：头痛（前额=阳明；巅顶=厥阴；两侧=少阳；后头部=太阳）', mnemonic: '胀气刺瘀冷寒灼热隐虚重湿酸痛虚；走窜气固瘀部归经', category: 'definition', tags_json: '["问诊","疼痛","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-109', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '望舌苔（苔质、苔色）的临床意义？', back_content: '苔质：\n薄厚→邪气深浅（薄=表证初期，厚=里证较深或食积）\n润燥→津液盈亏（润=津液未伤，燥=津伤）\n腻腐→湿浊内停（腻=湿浊，腐=食积化腐）\n剥脱→胃气阴亏损\n\n苔色：\n白=表证寒证；黄=里证热证；灰黑=热极或寒极', mnemonic: '苔→薄厚看深浅+润燥看津液+腻腐看湿食+剥脱看胃气+白黄灰看寒热', category: 'definition', tags_json: '["舌诊","苔诊","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-110', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-05', knowledge_point_ids_json: '[]', front_content: '寒热错杂证与寒热真假证的鉴别要点？', back_content: '寒热错杂：寒热同时存在（上热下寒/上寒下热/表寒里热/表热里寒）\n\n寒热真假鉴别：\n真寒假热（阴盛格阳）：虽面红如妆但下肢厥冷渴欲热饮但饮不多烦躁但精神萎靡脉浮大但按之无力\n真热假寒（阳盛格阴）：虽四肢厥冷但胸腹灼热不恶寒反恶热烦渴喜冷饮脉沉实有力\n\n关键：从里证根本性质和舌脉辨别。', mnemonic: '错杂→寒热同时存；真假→假象在外里证为主→舌脉辨', category: 'clinical', tags_json: '["八纲辨证","寒热","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-111', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-07', knowledge_point_ids_json: '[]', front_content: '气陷证与气脱证的概念及临床表现？', back_content: '气陷证：气虚升举无力反而下陷\n表现：头晕眼花少气乏力+腹部坠胀感+内脏下垂（胃下垂肾下垂脱肛子宫脱垂）+舌淡脉弱\n\n气脱证：气虚至极而欲脱的危重证\n表现：面色苍白大汗淋漓四肢厥冷气息微弱口开目合二便失禁脉微欲绝\n\n气陷为气虚之加重，气脱为气虚之危象。', mnemonic: '气陷→下垂坠胀；气脱→脱汗脱冷脱微→危重', category: 'definition', tags_json: '["气血辨证","气陷气脱"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-112', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-08', knowledge_point_ids_json: '[]', front_content: '卫气营血辨证各阶段的典型表现及代表方？', back_content: '卫分证：发热微恶风寒+头痛口渴+脉浮数——银翘散\n气分证：身大热汗大出口大渴脉洪大——白虎汤\n营分证：身热夜甚+心烦不寐+时有谵语+斑疹隐隐+舌红绛——清营汤\n血分证：斑疹显露+吐血衄血便血+躁扰发狂+舌深绛——犀角地黄汤', mnemonic: '卫→气→营→血：表→里→神→血→银翘→白虎→清营→犀角', category: 'clinical', tags_json: '["其他辨证","卫气营血","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-113', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-02', knowledge_point_ids_json: '[]', front_content: '闻诊中听声音的主要内容和临床意义？', back_content: '声音高低：声高有力=实证热证；声低无力=虚证寒证\n言语：谵语=热扰心神（实）；郑声=心气大伤（虚）；独语=心气不足或痰蒙心窍\n呼吸：喘=呼吸困难短促急迫（实喘邪实，虚喘正虚）；哮=喘而有声\n咳嗽：咳声重浊=实证；咳声低怯=虚证；干咳=燥热或阴虚', mnemonic: '闻声→高实低声+谵实郑虚+喘实哮鸣+咳重实轻虚', category: 'definition', tags_json: '["闻诊","听声音"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan3-114', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '望排出物（痰涎涕唾二便呕吐物）如何辨别寒热虚实？', back_content: '清稀量多色白→虚证寒证\n黄稠量少黏浊→实证热证\n痰：白清稀=寒痰；黄稠=热痰；痰少黏=燥痰；痰多易咯=湿痰\n涕：清稀=风寒；黄稠=风热\n呕吐物：清稀无臭=寒呕；秽浊酸臭=热呕/食积\n二便：清稀水样=寒湿；黄褐秽臭=湿热', mnemonic: '排出物→清白稀=寒虚，黄稠臭=热实→一般规律', category: 'definition', tags_json: '["望诊","望排出物"]', created_at: now, is_system: 1 },

    // ================================================================
    // 中药学 (15 cards) — zhongyao
    // ================================================================
    { id: 'fc-zhongyao3-100', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-03', knowledge_point_ids_json: '[]', front_content: '辛温解表药（发散风寒药）的常用药物及其功效要点？', back_content: '麻黄：发汗解表宣肺平喘利水消肿——风寒表实证首选\n桂枝：发汗解肌温通经脉助阳化气——风寒表虚实证均可\n紫苏：解表散寒行气和胃安胎——风寒感冒兼气滞\n荆芥：祛风解表透疹消疮止血——风寒风热均可("风药中之润剂")\n防风：祛风解表胜湿止痛止痉——风药中之上品', mnemonic: '麻黄发汗强桂枝通阳紫苏安胎荆芥兼风热防风风上品', category: 'herb', tags_json: '["解表药","辛温解表","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-101', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-04', knowledge_point_ids_json: '[]', front_content: '清热泻火药中石膏、知母、天花粉的比较？', back_content: '石膏：清热泻火力强——清肺胃实热（气分热盛之要药）\n知母：清热泻火+滋阴润燥——实热虚热均可（气分热盛+阴虚火旺）\n天花粉：清热生津+消肿排脓——热病津伤口渴及疮疡\n\n石膏+知母=白虎汤清阳明气分热\n知母+黄柏=知柏地黄丸滋阴降火', mnemonic: '石膏力最强清气分，知母兼滋阴，花粉生津消疮', category: 'herb', tags_json: '["清热药","清热泻火","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-102', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-04', knowledge_point_ids_json: '[]', front_content: '清热燥湿药黄芩、黄连、黄柏的鉴别（三黄）？', back_content: '黄芩：走上焦——清肺热止咳+安胎+止血（胎热不安、咯血衄血）\n黄连：走中焦——清心胃湿热（泻痢要药）+清心火（心烦失眠）\n黄柏：走下焦——清下焦湿热+退虚热（湿热下注、阴虚火旺）\n\n共性是均能清热燥湿泻火解毒。\n黄芩入肺，黄连入心胃，黄柏入肾。', mnemonic: '三黄→芩上肺+连中胃+柏下肾→上焦肺中焦心下焦肾', category: 'herb', tags_json: '["清热药","清热燥湿","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-103', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-04', knowledge_point_ids_json: '[]', front_content: '清热解毒药的常用药物及其特点？', back_content: '金银花：清热解毒+疏散风热——疮痈要药（治一切疮痈红肿热痛）\n连翘：清热解毒+消痈散结+疏散风热——疮家圣药（善治瘰疬痰核）\n蒲公英：清热解毒+消痈散结+利湿通淋——乳痈要药\n鱼腥草：清热解毒+消痈排脓+利尿通淋——肺痈要药（咳吐脓血）\n白头翁：清热解毒+凉血止痢——热毒血痢要药', mnemonic: '银花解风热散疮，连翘散结治瘰疬，公英乳痈鱼肺痈，翁治血痢', category: 'herb', tags_json: '["清热药","清热解毒","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-104', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-12', knowledge_point_ids_json: '[]', front_content: '补气药中人参、黄芪、白术、甘草的功效比较？', back_content: '人参：大补元气复脉固脱——气虚欲脱第一要药+补脾益肺\n黄芪：补气升阳益卫固表利水消肿托毒生肌——补气固表要药\n白术：健脾益气燥湿利水止汗安胎——健脾要药（脾虚湿盛首选）\n甘草：补脾益气清热解毒祛痰止咳缓急止痛调和诸药——"国老"调和百药\n\n四君子汤=参+术+苓+草（益气健脾基础方）。', mnemonic: '参大补元+芪固表升+术健脾湿+草调诸药', category: 'herb', tags_json: '["补虚药","补气药","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-105', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-12', knowledge_point_ids_json: '[]', front_content: '补血药当归、熟地、白芍、阿胶的功效区别？', back_content: '当归：补血活血调经止痛润肠通便——补血调经要药妇科圣药\n熟地：补血滋阴填精益髓——补血要药+滋肾阴主药\n白芍：养血敛阴柔肝止痛平抑肝阳——调经柔肝要药\n阿胶：补血止血滋阴润肺——补血止血要药（兼能润肺止咳）\n\n归地芎芍=四物汤（补血调血基础方）。', mnemonic: '归活血调经+地补精血+芍柔肝养血+胶止血润肺', category: 'herb', tags_json: '["补虚药","补血药","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-106', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-06', knowledge_point_ids_json: '[]', front_content: '利水渗湿药中茯苓、薏苡仁、泽泻、车前子的比较？', back_content: '茯苓：利水渗湿健脾宁心——性平利而不伤正（利水要药）\n薏苡仁：利水渗湿健脾除痹清热排脓——性凉微寒\n泽泻：利水渗湿泄热——利水力强于茯苓（泻肾与膀胱之热）\n车前子：利尿通淋渗湿止泻清肝明目清肺化痰\n\n茯苓薏苡仁兼健脾，泽泻偏泄热，车前善通淋。', mnemonic: '苓兼健脾安心神+薏兼除痹清热+泽泄力强+车前通淋', category: 'herb', tags_json: '["利水渗湿药","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-107', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-09', knowledge_point_ids_json: '[]', front_content: '活血化瘀药川芎、丹参、红花、桃仁、牛膝的功效比较？', back_content: '川芎：活血行气祛风止痛——上行头目下调经水（血中气药）\n丹参：活血调经凉血消痈安神——活血不伤正（妇科活血调经要药）\n红花：活血通经祛瘀止痛——少用活血多用破血\n桃仁：活血祛瘀润肠通便止咳平喘——瘀血伴便秘首选\n牛膝：活血通经补肝肾强筋骨利水通淋引血下行——下肢血瘀引经药', mnemonic: '芎气药+丹凉血+红破瘀+桃通便+膝引下行→各有侧重', category: 'herb', tags_json: '["活血化瘀药","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-108', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-05', knowledge_point_ids_json: '[]', front_content: '祛风湿药独活与羌活的功效鉴别？', back_content: '独活：祛风湿止痛解表——偏入肾经善治下半身风湿痹痛（腰膝腿足）\n羌活：祛风湿止痛解表——偏入膀胱经善治上半身风湿痹痛（项背）\n\n共性：均能祛风湿止痛解表治风寒湿痹。\n\n独活寄生汤（腰腿痛）vs 羌活胜湿汤（肩背痛）。\n口诀："羌上独下"，部位有别。', mnemonic: '羌上独下→羌活治上半身背项痛，独活治下半身腰腿痛', category: 'herb', tags_json: '["祛风湿药"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-109', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-02', knowledge_point_ids_json: '[]', front_content: '中药"十八反"和"十九畏"的主要内容？', back_content: '十八反歌诀：\n本草明言十八反，半蒌贝蔹及攻乌。\n藻戟遂芫俱战草，诸参辛芍叛藜芦。\n\n十九畏歌诀：\n硫黄原是火中精，朴硝一见便相争。\n水银莫与砒霜见，狼毒最怕密陀僧。\n巴豆性烈最为上，偏与牵牛不顺情。\n丁香莫与郁金见，牙硝难合荆三棱。\n川乌草乌不顺犀，人参最怕五灵脂。\n官桂善能调冷气，若逢石脂便相欺。\n\n凡此种种配伍禁忌应记牢。', mnemonic: '十八反：半蒌贝蔹及攻乌、藻戟遂芫俱战草、诸参辛芍叛藜芦', category: 'herb', tags_json: '["总论","配伍","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-110', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-11', knowledge_point_ids_json: '[]', front_content: '安神药的分型及代表药物？', back_content: '重镇安神药（治标）：\n朱砂：清心镇惊安神（有毒不宜久服）\n磁石：镇惊安神平肝潜阳聪耳明目纳气平喘\n龙骨：镇惊安神平肝潜阳收敛固涩\n\n养心安神药（治本）：\n酸枣仁：养心益肝安神敛汗——安神要药\n远志：安神益智祛痰开窍消肿\n柏子仁：养心安神润肠通便\n合欢皮：解郁安神活血消肿', mnemonic: '重镇→朱磁龙骨镇+安神→枣远柏欢养', category: 'herb', tags_json: '["安神药","分类","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-111', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-10', knowledge_point_ids_json: '[]', front_content: '止咳平喘药的分类及代表药物特征？', back_content: '温化寒痰：半夏（燥湿化痰降逆止呕）天南星（化痰散结祛风止痉）\n清化热痰：川贝母（润肺止咳）浙贝母（清热散结）瓜蒌（清热化痰宽胸散结）\n止咳平喘：苦杏仁（降气止咳平喘）苏子（降气平喘润肠）\n百部（润肺止咳杀虫）枇杷叶（清肺止咳降逆止呕）\n\n川贝偏润燥咳久咳，浙贝偏清热散结治热咳瘰疬。', mnemonic: '温→夏南；清→贝蒌；止→杏苏枇百→三类各有所主', category: 'herb', tags_json: '["化痰止咳平喘药"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-112', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-07', knowledge_point_ids_json: '[]', front_content: '理气药陈皮、木香、香附、枳实的功效区别？', back_content: '陈皮：理气健脾燥湿化痰——脾胃气滞通用药\n木香：行气止痛健脾消食——气滞腹痛要药\n香附：疏肝理气调经止痛——"气病之总司女科之主帅"（妇科调经要药）\n枳实：破气消积化痰散痞——气滞重症（食积便秘腹胀）\n\n陈皮行脾、香附疏肝、木香止痛、枳实破气。', mnemonic: '陈理脾+木止痛+香调肝经+枳破积→各有专长', category: 'herb', tags_json: '["理气药","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-113', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-08', knowledge_point_ids_json: '[]', front_content: '消食药山楂、神曲、麦芽、鸡内金的功效区别？', back_content: '山楂：消食化积行气散瘀——油腻肉食积滞要药\n神曲：消食和胃——米面食积（兼解表）\n麦芽：消食健胃回乳消胀——米面薯芋食积+回乳\n鸡内金：消食健胃涩精止遗化石通淋——各种食积（消食力最强）\n\n"焦三仙"=焦山楂+焦神曲+焦麦芽（消各种食积）。', mnemonic: '山肉积+曲面积+芽米积兼回乳+金全面力最强', category: 'herb', tags_json: '["消食药","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongyao3-114', subject_id: 'zhongyao', chapter_id: 'ch-zhongyao-01', knowledge_point_ids_json: '[]', front_content: '中药的炮制目的和常用炮制方法有哪些？', back_content: '目的：\n1. 增强药物疗效 2. 降低或消除毒副作用\n3. 改变药物性能 4. 便于制剂和贮藏\n5. 纯净药物保证质量 6. 矫味矫臭便于服用\n\n常用方法：\n修制（净制切制）、水制（洗泡润）、火制（炒炙煅煨）、水火共制（煮蒸淬）\n\n特殊：制霜、发酵、发芽等。', mnemonic: '炮制目的→增效减毒改性易贮净味→修水火共三法', category: 'herb', tags_json: '["总论","炮制"]', created_at: now, is_system: 1 },

    // ================================================================
    // 方剂学 (15 cards) — fangji
    // ================================================================
    { id: 'fc-fangji3-100', subject_id: 'fangji', chapter_id: 'ch-fangji-02', knowledge_point_ids_json: '[]', front_content: '解表剂中辛温解表与辛凉解表的代表方及主治？', back_content: '辛温解表：\n麻黄汤——风寒表实证（恶寒无汗脉浮紧）\n桂枝汤——风寒表虚证（恶风有汗脉浮缓）\n小青龙汤——外寒内饮证（恶寒咳喘痰多清稀）\n\n辛凉解表：\n银翘散——风热表证（发热咽痛舌尖红）\n桑菊饮——风热咳嗽（但咳身不甚热）\n麻杏石甘汤——外寒内热咳喘', mnemonic: '辛温→麻桂小青龙；辛凉→银桑麻杏甘→对症选方', category: 'formula', tags_json: '["解表剂","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-101', subject_id: 'fangji', chapter_id: 'ch-fangji-03', knowledge_point_ids_json: '[]', front_content: '和解剂中调和肝脾的常用方及鉴别？', back_content: '逍遥散：疏肝解郁+养血健脾——肝郁血虚脾弱（两胁作痛+食少神疲+月经不调）\n加味逍遥散（丹栀逍遥散）：逍遥散+丹皮栀子——肝郁化火（兼烦热）\n痛泻要方：补脾柔肝+祛湿止泻——脾虚肝旺之痛泻（肠鸣腹痛痛则即泻）\n四逆散：疏肝理脾——阳郁厥逆（四肢厥逆胁痛脉弦）', mnemonic: '逍遥疏肝健脾兼调经，痛泻止腹泻，四逆治阳郁', category: 'formula', tags_json: '["和解剂","调和肝脾","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-102', subject_id: 'fangji', chapter_id: 'ch-fangji-05', knowledge_point_ids_json: '[]', front_content: '四君子汤系列的化裁发展？', back_content: '四君子汤（参术苓草）——益气健脾（基础方）\n异功散=四君子+陈皮——益气健脾行气（兼气滞）\n六君子汤=四君子+陈皮半夏——健脾和胃化痰（兼痰湿）\n香砂六君子汤=六君子+木香砂仁——健脾和胃理气止痛（兼胃痛）\n参苓白术散=四君子+山药莲子扁豆薏仁砂仁桔梗——益气健脾渗湿止泻（脾虚泄泻）\n\n"四君子为补气之祖方"。', mnemonic: '四君→异功（+陈）→六君（+陈半）→香六（+香砂）→参苓（化裁）', category: 'formula', tags_json: '["补益剂","四君子系列","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-103', subject_id: 'fangji', chapter_id: 'ch-fangji-05', knowledge_point_ids_json: '[]', front_content: '四物汤系列的化裁发展？', back_content: '四物汤（归芎芍地）——补血调血（基础方）\n桃红四物汤=四物+桃仁红花——养血活血化瘀（血虚夹瘀）\n八珍汤=四君+四物——益气补血（气血两虚）\n十全大补汤=八珍+黄芪肉桂——温补气血（气血两虚偏寒）\n归脾汤=四君子+黄芪归眼远枣木香——益气补血健脾养心（心脾两虚）\n\n"四物为补血之祖方"。', mnemonic: '四物→桃红（+桃红）→八珍（+四君）→十全（+芪桂）→归脾（化裁）', category: 'formula', tags_json: '["补益剂","四物系列","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-104', subject_id: 'fangji', chapter_id: 'ch-fangji-05', knowledge_point_ids_json: '[]', front_content: '六味地黄丸的方解及三补三泻的意义？', back_content: '组成：熟地黄 山茱萸 山药 泽泻 牡丹皮 茯苓\n\n三补（补肾为主）：\n熟地——滋补肾阴填精益髓（君药）\n山茱萸——补益肝肾收敛固涩\n山药——补脾固肾\n\n三泻（以泻助补）：\n泽泻——泄肾浊（并防熟地滋腻）\n丹皮——清肝火（并制山茱萸之温）\n茯苓——渗脾湿（并助山药健脾）\n\n三补三泻=补中有泻以补为主。', mnemonic: '三补（地萸药补肾肝脾）三泻（泽丹苓泄浊火湿）→补大于泻', category: 'formula', tags_json: '["补益剂","六味地黄丸","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-105', subject_id: 'fangji', chapter_id: 'ch-fangji-05', knowledge_point_ids_json: '[]', front_content: '肾气丸与六味地黄丸的关系及区别？', back_content: '肾气丸（金匮肾气丸）=六味地黄丸+桂枝附子\n\n六味地黄丸：滋补肾阴——肾阴虚证（腰膝酸软头晕耳鸣盗汗）\n肾气丸：温补肾阳——肾阳虚证（腰膝冷痛畏寒肢冷小便不利或过多）\n\n"善补阳者必于阴中求阳"——肾气丸在补阴基础上加少量桂附→少火生气。\n\n后世演变：六味地黄丸（阴虚）+知柏地黄丸（阴虚火旺）+杞菊地黄丸（阴虚目暗）+麦味地黄丸（肺肾阴虚）。', mnemonic: '六味补阴→加桂附=肾气补阳→阴中求阳→少火生气', category: 'formula', tags_json: '["补益剂","肾气丸","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-106', subject_id: 'fangji', chapter_id: 'ch-fangji-07', knowledge_point_ids_json: '[]', front_content: '补阳还五汤的组方特点和用量特点？', back_content: '组成：生黄芪四两+当归尾+赤芍+地龙+川芎+桃仁+红花\n\n组方特点：\n1. 重用生黄芪（四两约120g）大补元气使气旺血行——君药\n2. 活血药用量很轻（归尾二钱赤芍一钱半等）——以补气为主活血为辅\n3. 使气旺血行瘀去络通——治中风后遗症之气虚血瘀证\n\n"不在逐瘀而在补气，不在破血而在行血"。', mnemonic: '重用芪→补气为主，轻用活血→以气带血→气虚血瘀中风', category: 'formula', tags_json: '["理血剂","补阳还五汤","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-107', subject_id: 'fangji', chapter_id: 'ch-fangji-06', knowledge_point_ids_json: '[]', front_content: '玉屏风散与桂枝汤均可治自汗，如何鉴别使用？', back_content: '玉屏风散：气虚表卫不固之自汗\n- 汗出恶风+面色白+易感冒\n- 治则：益气固表止汗（黄芪益气固表为君）\n\n桂枝汤：营卫不和之自汗\n- 汗出恶风+发热+脉浮缓\n- 治则：解肌发表调和营卫（桂枝解肌发表为君）\n\n鉴别要点：玉屏风无发热表证，纯属气虚不固；桂枝汤有表证（外感风邪）。', mnemonic: '玉屏虚汗无表证→补气固表；桂枝风汗有表证→解表调营', category: 'clinical', tags_json: '["固涩剂","鉴别","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-108', subject_id: 'fangji', chapter_id: 'ch-fangji-08', knowledge_point_ids_json: '[]', front_content: '羚角钩藤汤与大定风珠的鉴别？', back_content: '羚角钩藤汤：\n- 清热凉肝息风——肝经热盛动风（实风）\n- 高热抽搐+舌绛脉弦数\n- 治则：清热凉肝息风止痉\n\n大定风珠：\n- 滋阴养液柔肝息风——阴虚风动（虚风）\n- 手足蠕动+神倦脉虚舌绛少苔\n- 治则：滋阴息风（填补欲竭之真阴）\n\n鉴别：实风用清、虚风用补。', mnemonic: '羚角→清热息风实风；大定珠→滋阴息风虚风→虚实有别', category: 'formula', tags_json: '["治风剂","鉴别"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-109', subject_id: 'fangji', chapter_id: 'ch-fangji-09', knowledge_point_ids_json: '[]', front_content: '祛湿剂中平胃散与藿香正气散的鉴别？', back_content: '平胃散（苍术厚朴陈皮甘草）：\n- 燥湿运脾行气和胃\n- 主治湿滞脾胃证（脘腹胀满不思饮食口淡无味恶心呕吐）\n- 以中焦湿阻为主\n\n藿香正气散（藿香紫苏白芷厚朴陈皮半夏茯苓白术等）：\n- 解表化湿理气和中\n- 主治外感风寒内伤湿滞证（恶寒发热+脘腹胀痛+呕吐泄泻）\n- 兼有表证', mnemonic: '平胃纯化中焦湿，藿香解表又化湿→有无表证', category: 'formula', tags_json: '["祛湿剂","鉴别","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-110', subject_id: 'fangji', chapter_id: 'ch-fangji-04', knowledge_point_ids_json: '[]', front_content: '龙胆泻肝汤的组方配伍特点？', back_content: '组成：龙胆草+黄芩栀子+泽泻木通车前子+当归生地+柴胡+甘草\n\n配伍特点：\n1. 龙胆草大苦大寒直折肝胆实火——君药\n2. 黄芩栀子——助君泻火除湿——臣药\n3. 泽泻木通车前——利水渗湿使湿热从小便出\n4. 当归生地——养血滋阴以防苦寒伤阴\n5. 柴胡——引经入肝胆+疏肝\n\n苦寒清利为主，兼养血护阴。', mnemonic: '龙胆→芩栀助泻+泽通车利湿+归地护阴+柴引经→泻中有补', category: 'formula', tags_json: '["清热剂","龙胆泻肝汤","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-111', subject_id: 'fangji', chapter_id: 'ch-fangji-05', knowledge_point_ids_json: '[]', front_content: '归脾汤的主治和组方原理？', back_content: '主治：心脾两虚证（心悸失眠健忘食少体倦面色萎黄月经不调）+脾不统血证（便血崩漏）\n\n组方原理：\n人参黄芪白术甘草——益气补脾（治脾）\n当归龙眼肉——养血补心（治心）\n酸枣仁远志茯苓——宁心安神\n木香——理气醒脾以防补药滋腻\n生姜大枣——调和营卫\n\n心脾同治以补脾为主，气血双补以补气为先。', mnemonic: '归脾→参芪术草补脾+归眼补心+枣远苓安神+木香醒脾', category: 'formula', tags_json: '["补益剂","归脾汤","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-112', subject_id: 'fangji', chapter_id: 'ch-fangji-02', knowledge_point_ids_json: '[]', front_content: '小青龙汤中干姜细辛五味子配伍的意义？', back_content: '小青龙汤（麻黄桂枝干姜细辛五味子半夏芍药甘草）主治外寒内饮。\n\n干姜+细辛+五味子为核心配伍：\n- 干姜温肺化饮（温中以散寒饮）\n- 细辛温肺化饮+解表散寒（辛散走表）\n- 五味子敛肺止咳（酸收防辛散太过）\n\n三者一温一散一收——温化寒饮而不伤正散中有收。', mnemonic: '姜温+辛散+味收→温散收结合→化饮止咳核心', category: 'formula', tags_json: '["解表剂","小青龙汤","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-113', subject_id: 'fangji', chapter_id: 'ch-fangji-01', knowledge_point_ids_json: '[]', front_content: '方剂的剂型种类及各自特点？', back_content: '汤剂：吸收快起效速灵活加减——用于急性病（"汤者荡也"）\n散剂：制作简便吸收较快——用于外感轻症及慢性病（"散者散也"）\n丸剂：作用持久缓慢——用于慢性虚弱性疾病（"丸者缓也"）\n膏剂：内服膏剂滋补——外敷膏药治外科疾病\n丹剂：有汞等矿物精炼——多外用\n酒剂：酒能温通——用于风寒湿痹\n\n另有：冲剂、片剂、注射液等。', mnemonic: '汤→速散→快丸→缓膏→滋补丹→外用酒→温通', category: 'formula', tags_json: '["总论","剂型"]', created_at: now, is_system: 1 },
    { id: 'fc-fangji3-114', subject_id: 'fangji', chapter_id: 'ch-fangji-10', knowledge_point_ids_json: '[]', front_content: '保和丸与健脾丸在消食导滞方面的鉴别？', back_content: '保和丸：\n- 消食和胃——食积实证（病在胃）\n- 脘腹胀满嗳腐吞酸厌食呕逆\n- 以消为主（山楂神曲莱菔子配连翘）\n\n健脾丸：\n- 健脾和胃消食止泻——脾虚食积证（病在脾）\n- 食少难消脘腹痞闷大便溏薄\n- 消补兼施（四君子汤+消食药）\n\n鉴别：保和丸纯消纯实，健脾丸消补兼施（脾虚夹食）。', mnemonic: '保和纯消治实证，健脾消补治虚食→虚实之别', category: 'clinical', tags_json: '["消食剂","鉴别"]', created_at: now, is_system: 1 },

    // ================================================================
    // 西医内科学 (15 cards) — neike
    // ================================================================
    { id: 'fc-neike3-100', subject_id: 'neike', chapter_id: 'ch-neike-01', knowledge_point_ids_json: '[]', front_content: 'COPD的临床表现和诊断标准？', back_content: '临床表现：\n1. 慢性咳嗽咳痰（每年>3个月连续>2年）\n2. 进行性加重的呼吸困难\n3. 桶状胸（肺气肿体征）双肺呼吸音减弱\n\n诊断标准：\n1. 有吸烟等危险因素\n2. 肺功能检查：吸入支气管扩张剂后FEV1/FVC<70%可确诊\n3. 排除其他疾病', mnemonic: 'COPD→慢性咳痰+呼吸困难+FEV1/FVC<70%→肺功能金标准', category: 'clinical', tags_json: '["呼吸系统","COPD","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-101', subject_id: 'neike', chapter_id: 'ch-neike-02', knowledge_point_ids_json: '[]', front_content: '冠心病的分型和稳定型心绞痛的临床特点？', back_content: '冠心病分型：\n1. 慢性心肌缺血综合征（稳定型心绞痛、缺血性心肌病）\n2. 急性冠脉综合征（不稳定型心绞痛、非ST段抬高心梗、ST段抬高心梗）\n\n稳定型心绞痛特点：\n- 胸骨后压榨性疼痛持续3-5分钟\n- 劳累或情绪激动诱发\n- 休息或含服硝酸甘油可迅速缓解\n- 发作时ECG:ST段下移', mnemonic: '稳定→劳累诱发+休息缓解+ST下移；不稳定/心梗→>30分+持续不缓解', category: 'clinical', tags_json: '["循环系统","冠心病","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-102', subject_id: 'neike', chapter_id: 'ch-neike-02', knowledge_point_ids_json: '[]', front_content: '高血压病的危险分层和降压目标？', back_content: '危险分层（影响预后）：\n低危：1级高血压无其他危险因素\n中危：1-2个危险因素\n高危：3个以上危险因素或靶器官损害\n极高危：有临床并发症或糖尿病\n\n降压目标：\n一般目标：<140/90mmHg\n理想目标：<130/80mmHg（能耐受者）\n特殊人群：老年人<150/90mmHg；糖尿病/肾病<130/80mmHg', mnemonic: '分层→低中高极高；目标→140/90→130/80（理想）→老人≤150', category: 'clinical', tags_json: '["循环系统","高血压"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-103', subject_id: 'neike', chapter_id: 'ch-neike-03', knowledge_point_ids_json: '[]', front_content: '消化性溃疡的病因和临床表现要点？', back_content: '病因：\n1. 幽门螺杆菌（Hp）感染——最主要病因\n2. 非甾体抗炎药（NSAIDs）——药物性溃疡\n3. 胃酸和胃蛋白酶\n4. 其他：吸烟遗传应激\n\n胃溃疡 vs 十二指肠溃疡：\n胃溃疡：餐后0.5-1小时疼痛（餐后痛）+无夜间痛\n十二指肠溃疡：餐后2-3小时痛+夜间痛+进食后缓解+空腹痛', mnemonic: 'GU→餐后痛；DU→空腹痛夜间痛→GU在胃DU在肠', category: 'clinical', tags_json: '["消化系统","消化性溃疡","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-104', subject_id: 'neike', chapter_id: 'ch-neike-06', knowledge_point_ids_json: '[]', front_content: '糖尿病的诊断标准和分型要点？', back_content: '诊断标准（满足任一项）：\n1. 空腹血糖（FPG）>=7.0mmol/L\n2. OGTT 2h血糖>=11.1mmol/L\n3. HbA1c>=6.5%\n4. 典型症状+随机血糖>=11.1mmol/L\n\n分型：\n1型：自身免疫性胰岛beta细胞破坏——绝对胰岛素缺乏（好发于青少年酮症倾向）\n2型：胰岛素抵抗+胰岛素分泌相对不足——最常见（>90%）成年起病多肥胖', mnemonic: '诊断→7.0/11.1/6.5三项任一；分型→1型绝对缺2型相对缺', category: 'clinical', tags_json: '["内分泌","糖尿病","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-105', subject_id: 'neike', chapter_id: 'ch-neike-02', knowledge_point_ids_json: '[]', front_content: '心力衰竭的NYHA心功能分级？', back_content: 'NYHA分级（根据活动受限程度）：\nI级：日常活动无心衰症状（无心衰）\nII级：日常活动轻度受限（轻度心衰）\nIII级：低于日常活动即出现症状（中度心衰）\nIV级：休息时亦有症状（重度心衰）\n\n补充：\nA期：有心衰危险因素无结构改变\nB期：有结构改变无症状\nC期：有症状\nD期：终末期', mnemonic: 'I正常II轻度受限III显著受限IV静息有症→ABCD分期', category: 'clinical', tags_json: '["循环系统","心衰","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-106', subject_id: 'neike', chapter_id: 'ch-neike-07', knowledge_point_ids_json: '[]', front_content: '类风湿关节炎的临床表现和诊断要点？', back_content: '临床表现：\n1. 对称性多关节炎（近端指间关节掌指关节腕关节最常受累）\n2. 晨僵>=1小时（特征性表现）\n3. 关节外表现：类风湿结节（特异表现）、血管炎、肺间质病变\n4. 晚期：关节畸形（"鹅颈"畸形、"纽扣花"畸形）\n\n诊断：RF阳性抗CCP抗体（特异）CRP/ESR升高。', mnemonic: 'RA→对称小关节+晨僵+RF阳性+抗CCP→注意畸形', category: 'clinical', tags_json: '["风湿性疾病","类风湿关节炎"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-107', subject_id: 'neike', chapter_id: 'ch-neike-08', knowledge_point_ids_json: '[]', front_content: '缺血性脑卒中（脑梗死）的临床表现和治疗窗？', back_content: '临床表现：\n1. 突然起病（安静状态下多发）\n2. 偏瘫偏身感觉障碍偏盲（三偏征）\n3. 可有失语眩晕共济失调\n4. 意识障碍较轻（除非大面积梗死或脑干梗死）\n\n治疗时间窗：\n- 静脉溶栓：发病<4.5小时（rt-PA）\n- 血管内介入取栓：<6小时（部分可延至24小时）\n\n"时间就是大脑"。', mnemonic: '溶栓<4.5h取栓<6h→时间窗内分秒必争→三偏+突然', category: 'clinical', tags_json: '["神经系统","脑梗死","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-108', subject_id: 'neike', chapter_id: 'ch-neike-03', knowledge_point_ids_json: '[]', front_content: '肝硬化门脉高压的临床表现和并发症？', back_content: '门脉高压三大表现：\n1. 脾大脾功能亢进（全血细胞减少）\n2. 侧支循环开放：食管胃底静脉曲张（最危险）+腹壁静脉曲张+痔静脉扩张\n3. 腹水（最突出表现）\n\n并发症：\n1. 上消化道出血（食管胃底静脉曲张破裂）——最常见最凶险\n2. 肝性脑病——最严重的并发症和最常见的死亡原因\n3. 感染（自发性细菌性腹膜炎）\n4. 原发性肝癌', mnemonic: '门脉高压→脾大+侧支+腹水；并发症→出血+肝脑+感染+癌变', category: 'clinical', tags_json: '["消化系统","肝硬化","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-109', subject_id: 'neike', chapter_id: 'ch-neike-04', knowledge_point_ids_json: '[]', front_content: '慢性肾衰竭的分期标准（CKD分期）？', back_content: '按GFR（肾小球滤过率）分期：\nCKD1期：GFR>=90（肾损伤但GFR正常）\nCKD2期：GFR 60-89（轻度下降）\nCKD3期：GFR 30-59（中度下降）\nCKD4期：GFR 15-29（重度下降）\nCKD5期：GFR<15或透析（终末期肾病）\n\n评估指标：血肌酐、eGFR、尿蛋白定量', mnemonic: '12345→90→60→30→15→<15→数字记忆法', category: 'clinical', tags_json: '["泌尿系统","慢性肾衰竭"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-110', subject_id: 'neike', chapter_id: 'ch-neike-05', knowledge_point_ids_json: '[]', front_content: '贫血的形态学分类和常见病因？', back_content: '按MCV分：\n大细胞性贫血（MCV>100fL）：巨幼细胞性贫血（叶酸/B12缺乏）\n正常细胞性贫血（MCV 80-100fL）：再生障碍性贫血、急性失血、溶血性贫血\n小细胞低色素性贫血（MCV<80fL+低色素）：缺铁性贫血（最常见）、地中海贫血\n\n缺铁性贫血：血清铁降低总铁结合力升高铁蛋白降低\n\n补充：铁剂治疗至血红蛋白正常后再用3-6个月。', mnemonic: '大→叶B缺，正→再障失血溶血，小→缺铁地贫→MCV分', category: 'clinical', tags_json: '["血液系统","贫血","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-111', subject_id: 'neike', chapter_id: 'ch-neike-06', knowledge_point_ids_json: '[]', front_content: '甲亢的临床表现和Graves病的特征性表现？', back_content: '甲亢常见表现：\n- 高代谢症状：怕热多汗多食善饥消瘦\n- 交感神经兴奋：心悸手抖烦躁失眠\n- 甲状腺肿大\n- 突眼（Graves病特征）\n\nGraves病特征性表现：\n1. 弥漫性甲状腺肿（可伴血管杂音）\n2. 突眼（浸润性突眼）\n3. 胫前黏液性水肿\n4. TRAb阳性（特异性抗体）', mnemonic: '多食消瘦+手抖心悸+突眼+甲状腺肿+TRAb→Graves四特征', category: 'clinical', tags_json: '["内分泌","甲亢","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-112', subject_id: 'neike', chapter_id: 'ch-neike-01', knowledge_point_ids_json: '[]', front_content: '肺炎的分类和典型病原体？', back_content: '按环境分：\n社区获得性肺炎（CAP）：\n- 肺炎链球菌（最常见）\n- 肺炎支原体、肺炎衣原体（青壮年多见）\n- 流感嗜血杆菌\n\n医院获得性肺炎（HAP）：\n- G-杆菌（铜绿假单胞菌、大肠杆菌）\n- 金黄色葡萄球菌（包括MRSA）\n\n典型表现：发热咳嗽咳痰（铁锈色痰=肺炎链球菌）\n胸部X线：肺炎实变影。', mnemonic: 'CAP→链球+支衣；HAP→G-杆菌+金葡→按环境分', category: 'clinical', tags_json: '["呼吸系统","肺炎"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-113', subject_id: 'neike', chapter_id: 'ch-neike-04', knowledge_point_ids_json: '[]', front_content: '尿路感染的分类、临床表现和治疗？', back_content: '分类：\n下尿路感染（膀胱炎）：尿频尿急尿痛（膀胱刺激征）+可伴血尿\n上尿路感染（肾盂肾炎）：膀胱刺激征+发热寒战腰痛\n\n诊断：\n清洁中段尿培养菌落计数>=10^5/mL可确诊\nWBC>5/HP提示尿路感染\n\n治疗：\n急性膀胱炎：3天短程疗法（喹诺酮类/头孢类）\n急性肾盂肾炎：10-14天疗程', mnemonic: '膀胱炎→下尿路刺激；肾盂肾炎→膀胱症状+发热腰痛→上下有别', category: 'clinical', tags_json: '["泌尿系统","尿路感染"]', created_at: now, is_system: 1 },
    { id: 'fc-neike3-114', subject_id: 'neike', chapter_id: 'ch-neike-08', knowledge_point_ids_json: '[]', front_content: '癫痫发作的分类首选药物？', back_content: '全面性发作：\n全身强直-阵挛发作（大发作）——首选丙戊酸钠/卡马西平\n失神发作（小发作）——首选乙琥胺/丙戊酸钠\n肌阵挛发作——首选丙戊酸钠\n\n局灶性发作：\n首选卡马西平/奥卡西平\n\n癫痫持续状态：\n首选地西泮（安定）静脉推注\n\n注意事项：遵医嘱长期服药不可突然停药。', mnemonic: '大=丙戊卡马；小=乙琥；局部=卡马；持续状态=安定→不同发作不同首选', category: 'clinical', tags_json: '["神经系统","癫痫","重点"]', created_at: now, is_system: 1 },

    // ================================================================
    // 诊断学基础 (15 cards) — zhenduan
    // ================================================================
    { id: 'fc-zhenduan3-100', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-01', knowledge_point_ids_json: '[]', front_content: '常见热型及各自临床意义？', back_content: '稽留热：持续高热24h波动<1℃——大叶性肺炎、伤寒\n弛张热：24h波动>2℃最低仍高于正常——败血症、风湿热\n间歇热：发热与无热交替——疟疾、急性肾盂肾炎\n波状热：体温渐升渐降——布鲁菌病\n回归热：高热数天后降至正常数天后又高热——回归热\n不规则热：无规律——结核病、风湿热', mnemonic: '稽留>肺伤，弛张>败风，间歇>疟肾，波状>布病，回归>回归热', category: 'clinical', tags_json: '["症状","发热","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-101', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-02', knowledge_point_ids_json: '[]', front_content: '心脏瓣膜听诊区和常见杂音特点？', back_content: '听诊区：\n二尖瓣区：心尖部（第5肋间左锁骨中线内侧）\n主动脉瓣区：胸骨右缘第2肋间\n主动脉瓣第二听诊区：胸骨左缘第3肋间\n肺动脉瓣区：胸骨左缘第2肋间\n三尖瓣区：胸骨左缘第4、5肋间\n\n杂音：\n收缩期杂音（SM）——二尖瓣关闭不全、主动脉瓣狭窄\n舒张期杂音（DM）——二尖瓣狭窄、主动脉瓣关闭不全', mnemonic: '二主肺动三→收缩期=关闭不全+狭窄；舒张期=狭窄+关闭不全', category: 'clinical', tags_json: '["体格检查","心脏听诊","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-102', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-02', knowledge_point_ids_json: '[]', front_content: '肺部听诊的异常呼吸音及临床意义？', back_content: '干啰音：哨笛音（小气道狭窄——支气管哮喘）\n鼾音（大气道狭窄——气管异物肿瘤）\n\n湿啰音（水泡音）：\n大水泡音——肺水肿、大空洞\n中水泡音——支气管肺炎\n小水泡音——细支气管炎、肺炎\n捻发音——肺炎早期、肺淤血\n\nVelcro啰音（类似撕开尼龙搭扣的声音）——间质性肺病（特异性体征）', mnemonic: '干→哨笛鼾；湿→大中小检→不同部位疾病→Velcro=间质肺', category: 'clinical', tags_json: '["体格检查","肺部听诊"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-103', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-04', knowledge_point_ids_json: '[]', front_content: '肝功能检查的主要项目及临床意义？', back_content: '反映肝细胞损伤：ALT（丙氨酸氨基转移酶）主要存在于肝细胞浆\nAST（天门冬氨酸氨基转移酶）存在于肝细胞浆和线粒体\nALT/AST比值：急性肝炎ALT>AST，肝硬化AST>ALT\n\n反映胆红素代谢：TBil（总胆红素）DBil（直接胆红素）\n反映合成功能：Alb（白蛋白）PT（凝血酶原时间）\n反映胆汁淤积：ALP（碱性磷酸酶）GGT（γ-谷氨酰转肽酶）', mnemonic: '肝→ALT/AST（损伤）+TBil/DBil（黄疸）+Alb/PT（合成）+ALP/GGT（淤积）', category: 'clinical', tags_json: '["实验室检查","肝功能","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-104', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-05', knowledge_point_ids_json: '[]', front_content: '心肌梗死的心电图演变过程？', back_content: '超急性期（数分钟-数小时）：T波高尖\n急性期（数小时-数周）：ST段弓背向上抬高+病理性Q波+T波倒置\n亚急性期（数周-数月）：ST段逐渐回落至基线+T波倒置逐渐恢复\n陈旧期（数月后）：病理性Q波永久存在（心肌坏死标志）\n\n定位（根据导联）：\n前间壁=V1-V3；前壁=V3-V5；广泛前壁=V1-V6\n下壁=II、III、aVF；侧壁=I、aVL、V5-V6', mnemonic: 'T高→ST抬+Q+T倒→ST回→Q永留→导联定位', category: 'clinical', tags_json: '["心电图","心梗","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-105', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-04', knowledge_point_ids_json: '[]', front_content: '肾功能检查的主要指标及其临床意义？', back_content: '肾小球功能：\n血肌酐（Cr）：肌肉代谢产物经肾排出——升高提示GFR下降\n血尿素氮（BUN）：蛋白质代谢终产物——受饮食消化道出血等影响\n血尿酸（UA）：嘌呤代谢产物——升高提示肾功能减退及痛风\n估算GFR（eGFR）：评估肾小球滤过率金标准\n\n肾小管功能：\n尿比重、尿渗透压——反映浓缩稀释功能\n尿NAG酶——肾小管损伤标志物', mnemonic: '肾小球→Cr/BUN/UA/GFR；肾小管→比重/渗透/NAG酶', category: 'clinical', tags_json: '["实验室检查","肾功能"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-106', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-06', knowledge_point_ids_json: '[]', front_content: '常见影像学检查的选择原则？', back_content: 'X线：首选检查——骨骼系统、胸部疾病（肺炎肺结核气胸）\nCT：高分辨率——颅内出血、腹部病变、肺间质病变、外伤\nMRI：软组织分辨最佳——中枢神经系统、关节韧带、软组织肿瘤\n超声：无辐射操作方便——腹部脏器（肝胆胰脾肾）、妇产科、心脏\n核医学：功能显像（PET-CT）——肿瘤分期转移评估\n\n选择原则：由简到繁、首选敏感度和特异度最高的检查。', mnemonic: 'X线→骨胸；CT→颅内腹；MRI→中枢关节软组织；超声→腹产心', category: 'clinical', tags_json: '["影像学","选择原则"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-107', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-03', knowledge_point_ids_json: '[]', front_content: '腹部触诊的检查内容和异常发现？', back_content: '腹壁紧张度：板状腹=急性弥漫性腹膜炎（胃肠穿孔）\n揉面感=结核性腹膜炎\n\n压痛和反跳痛：\n局限性压痛=局部炎症\n反跳痛=腹膜炎体征（腹膜刺激征）\nMcBurney点压痛=急性阑尾炎\n\n脏器触诊：\n肝脏触诊：大小质地边缘表面压痛（正常肋下不能触及）\n脾脏触诊：脾大分级（轻度中度重度）\nMurphy征=急性胆囊炎', mnemonic: '腹触→紧张+压痛+反跳痛+脏器肿大→定位诊断', category: 'clinical', tags_json: '["体格检查","腹部触诊","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-108', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-04', knowledge_point_ids_json: '[]', front_content: '血常规主要指标的正常值及临床意义？', back_content: '红细胞（RBC）：男4.0-5.5x10^12/L，女3.5-5.0x10^12/L（减少=贫血）\n血红蛋白（Hb）：男120-160g/L，女110-150g/L\n白细胞（WBC）：4.0-10.0x10^9/L（增高=感染炎症白血病）\n中性粒细胞（N）：50-70%（增高=细菌感染）\n淋巴细胞（L）：20-40%（增高=病毒感染）\n血小板（PLT）：100-300x10^9/L（减少=出血风险 增高=血栓风险）', mnemonic: 'RBC/Hb→贫血；WBC→感染；N→细菌；L→病毒；PLT→出血/血栓', category: 'clinical', tags_json: '["实验室检查","血常规","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-109', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-05', knowledge_point_ids_json: '[]', front_content: '正常心电图的波形意义和各间期正常值？', back_content: 'P波：心房除极（<0.12s）\nPR间期：房室传导时间（0.12-0.20s）——延长=房室传导阻滞\nQRS波群：心室除极（0.06-0.10s）——增宽=室内传导阻滞\nST段：心室缓慢复极——抬高>0.1mV或压低>0.05mV为异常\nT波：心室快速复极——倒置=心肌缺血\nQT间期：心室除极+复极总时间——延长可致恶性心律失常（尖端扭转型室速）', mnemonic: 'P→PR→QRS→ST→T→QT→逐一分析→波形+间期=全局', category: 'clinical', tags_json: '["心电图","正常心电图","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-110', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-01', knowledge_point_ids_json: '[]', front_content: '咯血与呕血的鉴别要点？', back_content: '咯血（呼吸系统）：\n- 咳出喉部以下呼吸道出血\n- 血色鲜红+泡沫状+混有痰液\n- 多有咳嗽胸闷喉痒\n- 大便隐血阴性（除非咽下血液）\n\n呕血（消化系统）：\n- 呕出上消化道出血\n- 血色暗红或咖啡渣样\n- 混有食物残渣+酸性\n- 之后必有黑便\n\n关键鉴别：出血方式、血色、伴随物、黑便。', mnemonic: '咯→咳出鲜红泡沫痰液；呕→呕出暗红食物残渣黑便→呼吸道vs消化道', category: 'clinical', tags_json: '["症状","咯血呕血鉴别","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-111', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-02', knowledge_point_ids_json: '[]', front_content: '浅表淋巴结检查要点和临床意义？', back_content: '检查顺序：耳前后→颌下→颏下→颈部→锁骨上→腋窝→滑车上→腹股沟\n\n触诊要点：大小质地活动度有无压痛与周围组织有无粘连\n\n临床意义：\n局部淋巴结肿大：引流区域炎症或肿瘤转移\n- 左锁骨上淋巴结（Virchow淋巴结）肿大=胃癌等腹腔肿瘤转移\n全身淋巴结肿大：淋巴瘤、白血病、传染性单核细胞增多症\n质硬固定无痛=恶性肿瘤转移', mnemonic: '顺序↑→大小质地活动压痛粘连；左锁上=胃癌警示', category: 'clinical', tags_json: '["体格检查","淋巴结"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-112', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-03', knowledge_point_ids_json: '[]', front_content: '神经反射检查主要项目及异常意义？', back_content: '生理反射：\n浅反射：角膜反射腹壁反射提睾反射\n深反射：肱二头肌腱反射（C5-6）膝腱反射（L2-4）\n跟腱反射（S1-2）\n\n病理反射：\nBabinski征阳性：拇指背伸其余四趾扇形散开——提示锥体束损伤（上运动神经元病变）\n\n脑膜刺激征：\n颈项强直、Kernig征、Brudzinski征——脑膜炎、蛛网膜下腔出血', mnemonic: '浅→深→病理征（Babinski锥体束）→脑膜征→各层反射', category: 'clinical', tags_json: '["体格检查","神经系统","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-113', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-04', knowledge_point_ids_json: '[]', front_content: '乙肝病毒标志物（乙肝两对半）的解读？', back_content: 'HBsAg：提示HBV感染（最早出现的标志物）\n抗-HBs：保护性抗体——提示感染后免疫或疫苗接种后\nHBeAg：提示HBV复制活跃传染性强\n抗-HBe：病毒复制减少传染性降低\n抗-HBc：IgM（近期感染或活动期）IgG（既往感染）\n\n大三阳：HBsAg+HBeAg+抗-HBc——病毒复制活跃传染性强\n小三阳：HBsAg+抗-HBe+抗-HBc——病毒复制减少传染性较低', mnemonic: '表面→e抗原→e抗体→核心→大小三阳→根据e抗原/抗体区分', category: 'clinical', tags_json: '["实验室检查","乙肝","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenduan3-114', subject_id: 'zhenduan', chapter_id: 'ch-zhenduan-06', knowledge_point_ids_json: '[]', front_content: '正常胸部X线片的阅读步骤和内容？', back_content: '阅读步骤（ABCDEF法）：\nAirway（气管）：位置居中\nBreathing（肺）：肺纹理肺野透亮度有无浸润结节空洞\nCirculation（心脏大血管）：心影大小形态心胸比<0.5\nDiaphragm（横膈）：右膈略高于左膈肋膈角锐利\nEverything else（骨骼软组织）：肋骨锁骨胸椎有无骨折破坏\n\n重点：双侧对比对称性观察。', mnemonic: 'ABCDE→气管+肺+心脏+横膈+骨骼→系统阅读不遗漏', category: 'clinical', tags_json: '["影像学","胸片阅读"]', created_at: now, is_system: 1 },

    // ================================================================
    // 医学伦理学 (15 cards) — lunli
    // ================================================================
    { id: 'fc-lunli3-100', subject_id: 'lunli', chapter_id: 'ch-lunli-01', knowledge_point_ids_json: '[]', front_content: '医学伦理学的基本原则是什么？', back_content: '1. 尊重原则（自主原则）：尊重患者自主决定权（知情同意是核心体现）\n2. 不伤害原则：医疗行为不给患者造成本可避免的伤害（"首先不伤害"）\n3. 有利原则：医疗行为对患者有利，促进其健康和福利（"为病人利益着想"）\n4. 公正原则：公平对待每一位患者，公平分配医疗资源\n\n四大原则之间的冲突常需权衡和协调。', mnemonic: '四大原则→尊重（自主）+不伤害+有利+公正→ABCD原则', category: 'regulation', tags_json: '["伦理学概论","基本原则","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-101', subject_id: 'lunli', chapter_id: 'ch-lunli-02', knowledge_point_ids_json: '[]', front_content: '患者的权利主要包括哪些？', back_content: '1. 生命权与健康权（最基本权利）\n2. 知情权：了解病情诊疗措施和风险\n3. 自主决定权：知情同意后自主选择诊疗方案（包括拒绝治疗权）\n4. 隐私权：个人隐私受到保护\n5. 平等医疗权：不因种族性别年龄贫富等因素受歧视\n6. 损害赔偿权：因医疗过错造成损害时有权获得赔偿\n7. 查阅复印病历资料权', mnemonic: '七项权利→生命+知情+自主+隐私+平等+赔偿+查阅', category: 'regulation', tags_json: '["医患关系","患者权利","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-102', subject_id: 'lunli', chapter_id: 'ch-lunli-02', knowledge_point_ids_json: '[]', front_content: '知情同意的含义、要素和例外情况？', back_content: '含义：患者经充分告知后在理解基础上自主做出医疗决定。\n\n要素：\n1. 信息的告知（充分、真实、易懂）\n2. 信息的理解（确保患者真正理解）\n3. 自愿的同意（无强迫、欺诈、胁迫）\n4. 同意的能力（成年、意识清醒、有判断力）\n\n例外（可免除知情同意）：\n1. 危及生命的紧急情况\n2. 患者放弃知情同意权\n3. 法律规定（传染病强制隔离治疗等）', mnemonic: '四要素→告知理解自愿能力；例外→紧急放弃法定', category: 'regulation', tags_json: '["医患关系","知情同意","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-103', subject_id: 'lunli', chapter_id: 'ch-lunli-02', knowledge_point_ids_json: '[]', front_content: '保护性医疗制度（医疗保密）的原则和范围？', back_content: '保护性医疗制度要求保护患者隐私不过度公开病情信息。\n\n保密内容：\n1. 患者个人信息\n2. 病情和诊疗信息\n3. 医疗文书和记录\n\n保密例外（可披露）：\n1. 法律要求（传染病报告、犯罪线索等）\n2. 患者同意\n3. 保护第三方利益（如患者威胁伤害他人）\n4. 保护公共利益\n\n"有时去治愈常常去帮助总是去安慰"。', mnemonic: '保密→个人信息+病情+文书；例外→法律+同意+保护第三方+公益', category: 'regulation', tags_json: '["医患关系","保密制度"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-104', subject_id: 'lunli', chapter_id: 'ch-lunli-03', knowledge_point_ids_json: '[]', front_content: '临床诊疗中的伦理要求有哪些？', back_content: '诊断中的伦理要求：\n1. 合理检查（不过度检查不遗漏必要检查）\n2. 及时准确诊断\n3. 尊重患者隐私\n\n治疗中的伦理要求：\n1. 合理用药（安全有效经济——不滥用抗生素激素）\n2. 合理选择手术适应证\n3. 尊重患者知情同意权\n\n急危重症救治伦理：\n1. 救急不救"贫"（不以付费能力决定救治）\n2. 生命优先、时间优先', mnemonic: '诊疗伦理→合理检查+合理用药+尊重患者+急危生命优先', category: 'regulation', tags_json: '["临床伦理","诊疗伦理"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-105', subject_id: 'lunli', chapter_id: 'ch-lunli-04', knowledge_point_ids_json: '[]', front_content: '人体试验的伦理原则（赫尔辛基宣言要点）？', back_content: '1. 知情同意原则：受试者充分知情后自愿同意\n2. 有利无伤原则：对受试者利大于弊，伤害最小化\n3. 科学性原则：有充分科学依据，设计合理\n4. 伦理审查原则：须经独立伦理委员会审查批准\n5. 弱势群体保护：对孕妇、儿童、囚犯等特殊保护\n6. 试验中止原则：出现严重不良反应及时中止\n7. 结果公开原则：阴性结果也应发表', mnemonic: '知情+有利无伤+科学+审查+弱势保护+中止+公开→七项原则', category: 'regulation', tags_json: '["科研伦理","人体试验","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-106', subject_id: 'lunli', chapter_id: 'ch-lunli-04', knowledge_point_ids_json: '[]', front_content: '器官移植的伦理原则？', back_content: '1. 自愿无偿原则：活体器官捐献须完全自愿无偿（禁止器官买卖）\n2. 知情同意原则：供者和受者充分知情\n3. 公平分配原则：按医学标准和等待时间公平分配器官\n4. 不伤害原则：活体供者手术风险最小化\n5. 死亡判定标准：脑死亡标准（避免"活体摘除"嫌疑）\n6. 保密原则：供受双方信息保密\n\n禁止：活人器官买卖、强制摘取、未成年人活体捐献。', mnemonic: '自愿+无偿+公平分配+不伤害+脑死亡标准+保密→禁止买卖', category: 'regulation', tags_json: '["科研伦理","器官移植","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-107', subject_id: 'lunli', chapter_id: 'ch-lunli-01', knowledge_point_ids_json: '[]', front_content: '医德评价的标准和方式？', back_content: '评价标准：\n1. 医疗行为是否有利于患者疾病缓解和健康恢复（首要标准）\n2. 是否符合医学科学规律\n3. 是否有利于医学发展和社会进步\n\n评价方式：\n1. 社会舆论（外部监督）\n2. 内心信念（自我约束）\n3. 传统习俗（行业习惯）\n\n三者共同作用：社会舆论是外部监督，内心信念是内在动力。', mnemonic: '三标准→利患者+合科学+促发展；三方式→舆论+信念+习俗', category: 'regulation', tags_json: '["伦理学概论","医德评价"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-108', subject_id: 'lunli', chapter_id: 'ch-lunli-04', knowledge_point_ids_json: '[]', front_content: '辅助生殖技术的伦理问题有哪些？', back_content: '1. 胚胎的道德地位问题（多余的胚胎如何处理）\n2. 亲子关系认定（辅助生殖子女的法律父母是谁）\n3. 代孕的伦理争议（我国禁止代孕）\n4. 配子捐赠的匿名与知情权\n5. 优生与性别选择（非医学需要的性别选择被禁止）\n6. 单身女性/同性伴侣的生育权利\n\n我国原则：\n- 夫精人工授精准许\n- 供精人工授精有条件许（须书面知情同意）\n- 禁止代孕', mnemonic: '胚胎地位+亲子关系+代孕禁止+匿名vs知情+性别选择禁止', category: 'regulation', tags_json: '["科研伦理","辅助生殖"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-109', subject_id: 'lunli', chapter_id: 'ch-lunli-02', knowledge_point_ids_json: '[]', front_content: '医患沟通的技巧和原则？', back_content: '沟通原则：\n1. 尊重原则——以尊重的态度对待患者\n2. 诚信原则——诚实告知病情（适当履行保护性医疗）\n3. 共情原则——站在患者角度理解感受\n4. 易懂原则——用通俗语言解释医学术语\n\n沟通技巧：\n1. 认真倾听（不打断）\n2. 开放式提问\n3. 适当的肢体语言（眼神接触点头微笑）\n4. 总结反馈（确认患者理解）\n5. 告知坏消息时注意技巧（逐步告知、保留希望）', mnemonic: '四原则→尊重诚信共情易懂；五技巧→倾听开放肢体反馈坏消息', category: 'regulation', tags_json: '["医患关系","沟通技巧"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-110', subject_id: 'lunli', chapter_id: 'ch-lunli-03', knowledge_point_ids_json: '[]', front_content: '临终关怀的伦理理念和原则？', back_content: '理念：对临终患者提供全方位的关怀以提高生命最后阶段的质量。\n\n原则：\n1. 尊重生命：承认死亡是生命自然过程（不加速也不推迟死亡）\n2. 减轻痛苦：以控制疼痛和其他症状为首要目标\n3. 心理关怀：关注患者心理和精神需求\n4. 家属支持：对家属提供哀伤辅导\n\n与安乐死的区别：\n临终关怀=缓解痛苦自然走向死亡（合法）\n安乐死=主动结束生命（大部分国家不合法包括中国）', mnemonic: '临终关怀→尊重生命+减轻痛苦+心理精神+家属→非安乐死', category: 'regulation', tags_json: '["临床伦理","临终关怀","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-111', subject_id: 'lunli', chapter_id: 'ch-lunli-04', knowledge_point_ids_json: '[]', front_content: '基因伦理的主要议题有哪些？', back_content: '1. 基因隐私权：基因信息属于个人隐私（禁止基因歧视）\n2. 基因检测的知情同意：检测前须充分告知并获取同意\n3. 基因编辑伦理：体细胞基因治疗可接受但生殖细胞基因编辑争议巨大（除治疗外禁止基因增强）\n4. 克隆人伦理：全面禁止生殖性克隆（治疗性克隆存在伦理争议）\n5. 优生伦理：禁止强制优生尊重生育自主权\n\n核心：科技发展不能逾越伦理底线。', mnemonic: '基因伦理→隐私+知情+编辑红线+克隆禁止+优生自主', category: 'regulation', tags_json: '["科研伦理","基因伦理"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-112', subject_id: 'lunli', chapter_id: 'ch-lunli-01', knowledge_point_ids_json: '[]', front_content: '医学伦理学的历史发展里程碑有哪些？', back_content: '1. 希波克拉底誓言（古希腊）：西方医学伦理学起源——"首先不伤害"\n2. 纽伦堡法典（1947年）：人类受试者研究的第一个国际伦理准则——知情同意\n3. 赫尔辛基宣言（1964年首次发布多次修订）：人体试验的伦理准则\n4. 《日内瓦宣言》：现代版的希波克拉底誓言\n5. 世界医学学会《国际医学伦理准则》\n\n中国：《大医精诚》（孙思邈）——中医伦理传统经典。', mnemonic: '希波→纽伦→赫尔辛→日内瓦→WMA准则；中医→大医精诚', category: 'regulation', tags_json: '["伦理学概论","历史发展"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-113', subject_id: 'lunli', chapter_id: 'ch-lunli-03', knowledge_point_ids_json: '[]', front_content: '精神卫生领域的特殊伦理要求？', back_content: '1. 非自愿住院标准：有自伤或伤人的危险且无法在社区中进行治疗（须严格依法）\n2. 知情同意：有决定能力的患者须获取知情同意\n3. 保护性约束：仅当患者有自伤伤人危险时且其他方法无效——须记录、定期评估\n4. 隐私保护：精神疾病患者的隐私高度敏感\n5. 社会回归权利：促进患者康复回归社会\n6. 反歧视：不得歧视精神疾病患者', mnemonic: '非自愿严格+知情同意+约束有限+隐私保护+回归社会+反歧视', category: 'regulation', tags_json: '["临床伦理","精神卫生"]', created_at: now, is_system: 1 },
    { id: 'fc-lunli3-114', subject_id: 'lunli', chapter_id: 'ch-lunli-04', knowledge_point_ids_json: '[]', front_content: '动物实验的伦理原则（3R原则）？', back_content: '3R原则是动物实验伦理的核心：\n\n1. Replacement（替代）：\n尽可能用非动物方法替代活体动物实验（细胞培养计算机模型）\n\n2. Reduction（减少）：\n在保证科学性的前提下尽量减少使用动物数量\n\n3. Refinement（优化）：\n优化实验流程减少动物痛苦和伤害（麻醉镇痛改善环境）\n\n补充：实验动物福利要求"五项自由"（免于饥渴不适痛苦恐惧自由表达天性）。', mnemonic: '3R→替代(Replace)+减少(Reduce)+优化(Refine)→保护动物', category: 'regulation', tags_json: '["科研伦理","动物实验"]', created_at: now, is_system: 1 },

    // ================================================================
    // Additional abbreviated sections to reach 210+ cards across all 14 subjects
    // 中医内科学 (15 cards) — zhongnei
    // ================================================================
    { id: 'fc-zhongnei3-100', subject_id: 'zhongnei', chapter_id: 'ch-zhongnei-01', knowledge_point_ids_json: '[]', front_content: '感冒的辨证分型和代表方？', back_content: '1. 风寒束表证：恶寒重发热轻无汗——荆防败毒散\n2. 风热犯表证：发热重恶寒轻有汗——银翘散\n3. 暑湿伤表证：身热少汗肢体困重——新加香薷饮\n4. 气虚感冒：恶寒发热反复——参苏饮\n5. 阴虚感冒：身热微恶风寒——加减葳蕤汤\n\n"有一分恶寒便有一分表证"。', mnemonic: '风寒→荆防，风热→银翘，暑湿→香薷，气虚→参苏，阴虚→葳蕤', category: 'clinical', tags_json: '["肺系病证","感冒","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongnei3-101', subject_id: 'zhongnei', chapter_id: 'ch-zhongnei-01', knowledge_point_ids_json: '[]', front_content: '咳嗽的辨证要点和外感咳嗽与内伤咳嗽的鉴别？', back_content: '外感咳嗽：起病急病程短+伴表证（恶寒发热头痛脉浮）+多属实证\n- 风寒袭肺：三拗汤合止嗽散\n- 风热犯肺：桑菊饮\n- 风燥伤肺：桑杏汤\n\n内伤咳嗽：起病缓病程长+无表证+反复发作可伴他脏表现\n- 痰湿蕴肺：二陈汤合三子养亲汤\n- 痰热郁肺：清金化痰汤\n- 肝火犯肺：黛蛤散合黄芩泻白散\n- 肺阴亏虚：沙参麦冬汤', mnemonic: '外感急短有表→风寒三拗热桑菊燥桑杏；内伤缓长无表→痰湿二陈热清金', category: 'clinical', tags_json: '["肺系病证","咳嗽","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongnei3-102', subject_id: 'zhongnei', chapter_id: 'ch-zhongnei-02', knowledge_point_ids_json: '[]', front_content: '胸痹与真心痛的区别和联系？', back_content: '胸痹：胸部闷痛甚则胸痛彻背喘息不得卧（轻症）\n病因：寒邪内侵+饮食不节+情志失调+年老体虚→心脉痹阻\n\n真心痛：（"心痛甚手足青至节旦发夕死夕发旦死"）\n- 胸痹的危重证——相当于急性心肌梗死\n- 胸痛剧烈持续时间长（>30分钟）\n- 含服硝酸甘油不缓解\n- 可伴心悸怔忡大汗淋漓四肢厥冷脉微欲绝\n\n联系：真心痛为胸痹之极重证型。', mnemonic: '胸痹→闷痛持续可缓解；真心痛→彻心痛>30分不缓解→危重', category: 'clinical', tags_json: '["心系病证","胸痹","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongnei3-103', subject_id: 'zhongnei', chapter_id: 'ch-zhongnei-03', knowledge_point_ids_json: '[]', front_content: '泄泻的辨证论治要点和分型？', back_content: '暴泻（急性）：\n寒湿泄泻——藿香正气散（大便清稀+腹痛肠鸣+苔白腻）\n湿热泄泻——葛根芩连汤（泻下急迫色黄褐臭秽+肛门灼热）\n食滞泄泻——保和丸（大便臭如败卵+嗳腐吞酸）\n\n久泻（慢性）：\n肝气乘脾——痛泻要方（腹痛则泻泻后痛减+与情志有关）\n脾胃虚弱——参苓白术散（大便时溏时泻+食少神疲）\n肾阳虚衰——四神丸（五更泻+脐腹冷痛）', mnemonic: '暴泻→寒藿热葛食保；久泻→肝痛脾参肾四→急缓分治', category: 'clinical', tags_json: '["脾胃病证","泄泻","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongnei3-104', subject_id: 'zhongnei', chapter_id: 'ch-zhongnei-04', knowledge_point_ids_json: '[]', front_content: '中风的辨证要点（中经络与中脏腑的鉴别）？', back_content: '中经络：神志清楚+半身不遂口眼歪斜舌强语謇（病位较浅）\n- 风痰入络：真方白丸子\n- 风阳上扰：天麻钩藤饮\n- 阴虚风动：镇肝息风汤\n\n中脏腑：神志不清（昏仆）——危重证\n- 闭证：牙关紧闭两手握固（实证）\n  - 阳闭（热象）：安宫牛黄丸\n  - 阴闭（寒象）：苏合香丸\n- 脱证：口开手撒二便失禁（虚证）——参附汤合生脉散', mnemonic: '经→神清偏瘫；脏→昏迷→闭实脱虚→急则治标', category: 'clinical', tags_json: '["肝胆病证","中风","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongnei3-105', subject_id: 'zhongnei', chapter_id: 'ch-zhongnei-05', knowledge_point_ids_json: '[]', front_content: '水肿阴水和阳水的鉴别？', back_content: '阳水：发病急病程短+从头面开始肿（伴表证）+皮色光亮如新卧蚕状——实证热证\n风水相搏：越婢加术汤\n湿热壅盛：疏凿饮子\n\n阴水：发病慢病程长+从下肢开始肿+面色萎黄神疲乏力——虚证寒证\n脾阳虚：实脾饮\n肾阳虚：真武汤\n\n鉴别要点：发病快慢、始肿部位、皮色舌脉。', mnemonic: '阳水→急上实（越婢疏凿）；阴水→慢下虚（实脾真武）→上下虚实', category: 'clinical', tags_json: '["肾系病证","水肿","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongnei3-106', subject_id: 'zhongnei', chapter_id: 'ch-zhongnei-06', knowledge_point_ids_json: '[]', front_content: '郁证的病因病机和常见证型？', back_content: '病因：情志失调（忧郁恼怒思虑）→肝失疏泄脾失健运心失所养气血失调\n\n常见证型：\n1. 肝气郁结证：柴胡疏肝散（精神抑郁+胸胁胀痛）\n2. 气郁化火证：丹栀逍遥散（急躁易怒口苦口干）\n3. 痰气郁结证（梅核气）：半夏厚朴汤（咽中如有物阻）\n4. 心神失养证（脏躁）：甘麦大枣汤（精神恍惚悲伤欲哭）\n5. 心脾两虚证：归脾汤（多思善疑心悸失眠）', mnemonic: '郁→肝气+火+痰+心神+心脾→柴+丹栀+半厚+甘麦+归脾', category: 'clinical', tags_json: '["气血津液病证","郁证","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongnei3-107', subject_id: 'zhongnei', chapter_id: 'ch-zhongnei-07', knowledge_point_ids_json: '[]', front_content: '痹证的主要证型和代表方？', back_content: '痹证分型（按病因分）：\n行痹（风邪为主）：关节游走性疼痛——防风汤\n痛痹（寒邪为主）：关节剧痛遇寒加重——乌头汤\n着痹（湿邪为主）：关节重着肿胀——薏苡仁汤\n\n久痹（按病理分）：\n风湿热痹（热痹）：关节红肿灼热——白虎加桂枝汤合宣痹汤\n痰瘀痹阻证：关节肿大畸形顽痹久痹——双合汤\n肝肾亏虚证：痹证日久腰膝酸软——独活寄生汤', mnemonic: '行风→防，痛寒→乌，着湿→薏，热→白宣，顽痹→双合，久虚→独寄', category: 'clinical', tags_json: '["肢体经络病证","痹证","高频"]', created_at: now, is_system: 1 },

    // ================================================================
    // 中医外科学 (15 cards) — zhongwai
    // ================================================================
    { id: 'fc-zhongwai3-100', subject_id: 'zhongwai', chapter_id: 'ch-zhongwai-01', knowledge_point_ids_json: '[]', front_content: '疮疡的阴阳辨证要点？', back_content: '阳证疮疡：红肿热痛+高肿根束+皮色红赤+脓液稠黄+肉芽红活——易消易溃易敛\n代表疾病：痈\n\n阴证疮疡：漫肿无头+皮色不变淡白/晦暗+疼痛不明显+脓液稀薄+肉芽淡白——难消难溃难敛\n代表疾病：疽\n\n半阴半阳证：介于阴阳之间——如流注（漫肿微热皮色不变但化脓快）', mnemonic: '阳→红热痛脓稠→易愈；阴→暗漫凉脓稀→难愈→阴阳对立', category: 'clinical', tags_json: '["外科总论","阴阳辨证","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongwai3-101', subject_id: 'zhongwai', chapter_id: 'ch-zhongwai-02', knowledge_point_ids_json: '[]', front_content: '痈、疽、疔、疖的鉴别要点？', back_content: '疖：单个毛囊及皮脂腺感染——范围小（<3cm）浅表\n痈：多个相邻毛囊及皮脂腺的化脓性炎症——范围较大红肿热痛界限清\n有头疽：多个脓头状如蜂窝（多个毛囊深部同时感染）\n疽：深部脓肿——漫肿无头皮色不变或不泽（阴证）\n疔：颜面手足部的深部毛囊及周围组织急性化脓性感染——根脚深硬如钉（"面无疔疮"）', mnemonic: '疖小痈单疽阴疔深疽暗→从小到大由浅入深', category: 'clinical', tags_json: '["疮疡","鉴别","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongwai3-102', subject_id: 'zhongwai', chapter_id: 'ch-zhongwai-05', knowledge_point_ids_json: '[]', front_content: '常见皮肤病的辨证论治要点？', back_content: '湿疹（湿疮）：湿热浸淫=龙胆泻肝汤；脾虚湿蕴=除湿胃苓汤；血虚风燥=当归饮子\n\n荨麻疹（瘾疹）：风寒束表=麻黄桂枝各半汤；风热犯表=消风散\n\n牛皮癣（神经性皮炎）：肝郁化火=龙胆泻肝汤；风湿蕴肤=消风散；血虚风燥=当归饮子\n\n蛇串疮（带状疱疹）：清肝泻火解毒止痛=龙胆泻肝汤\n\n粉刺（痤疮）：肺经风热=枇杷清肺饮；肠胃湿热=茵陈蒿汤', mnemonic: '湿疹→湿热龙胆；瘾疹→风热消风；蛇串→龙胆；粉刺→枇杷', category: 'clinical', tags_json: '["皮肤病","辨证论治"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongwai3-103', subject_id: 'zhongwai', chapter_id: 'ch-zhongwai-03', knowledge_point_ids_json: '[]', front_content: '乳痈（急性乳腺炎）的分期论治？', back_content: '郁乳期（初期）：乳房胀痛乳汁不畅皮色不变——瓜蒌牛蒡汤（疏肝清胃通乳散结）\n\n成脓期：乳房红肿热痛明显+波动感——透脓散（托毒透脓）+切开引流\n\n溃后期：脓液流出肿消痛减——四君子汤合四物汤（调补气血生肌收口）\n\n外治法：\n- 初期：如意金黄散外敷\n- 成脓：切开引流\n- 溃后：九一丹药线引流', mnemonic: '郁→瓜蒌散；脓→透脓散+切开；溃→四君四物+外治→三期三步', category: 'clinical', tags_json: '["乳房疾病","乳痈"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongwai3-104', subject_id: 'zhongwai', chapter_id: 'ch-zhongwai-06', knowledge_point_ids_json: '[]', front_content: '痔疮的分类和辨证论治？', back_content: '内痔：齿线以上——无痛性便血+脱出（分期：I便血无脱出II便血脱出可回纳III须手推回）\n外痔：齿线以下——疼痛为主\n混合痔：跨齿线上下\n\n内痔辨证：\n风伤肠络：凉血地黄汤\n湿热下注：脏连丸\n气滞血瘀：止痛如神汤\n脾虚气陷：补中益气汤\n\n外治：消痔膏、枯痔钉、痔疮栓、熏洗法等。', mnemonic: '内出外痛混有两→内痔便血为主要；风凉湿脏瘀止痛虚中气→四证四法', category: 'clinical', tags_json: '["肛门直肠疾病","痔"]', created_at: now, is_system: 1 },

    // ================================================================
    // 中医妇科学 (15 cards) — zhongfu
    // ================================================================
    { id: 'fc-zhongfu3-100', subject_id: 'zhongfu', chapter_id: 'ch-zhongfu-01', knowledge_point_ids_json: '[]', front_content: '女性生殖功能的基本理论（天癸-冲任-胞宫轴）？', back_content: '肾-天癸-冲任-胞宫轴：\n\n肾藏精主生殖（先天之本）\n↓\n肾气盛→天癸至（天癸=促进生殖功能的物质）\n↓\n天癸→激发冲任二脉（冲为血海任主胞胎）\n↓\n冲任气血充盛→胞宫血海按时满溢→月经按时而至\n↓\n"女子二七天癸至任脉通太冲脉盛月事以时下故有子"', mnemonic: '肾→天癸→冲任→胞宫→月经→生殖功能链', category: 'definition', tags_json: '["总论","生理","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongfu3-101', subject_id: 'zhongfu', chapter_id: 'ch-zhongfu-02', knowledge_point_ids_json: '[]', front_content: '月经先期、后期、先后无定期的辨证论治？', back_content: '月经先期：气虚（补中益气汤）血热（清经散阴虚两地汤）\n月经后期：血寒（温经汤）血虚（大补元煎）气滞（乌药汤）\n月经先后无定期：肝郁（逍遥散）肾虚（固阴煎）\n\n月经病辨治要点：\n- 重在调经治本\n- 分清先病后病（先病经病先治经后治病；先病他病先治病后调经）\n- "调经以平为期"', mnemonic: '先期→气虚补中+血热清经；后期→血寒温经+血虚大补+气滞乌药；无定期→肝郁逍遥+肾虚固阴', category: 'clinical', tags_json: '["月经病","调经","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongfu3-102', subject_id: 'zhongfu', chapter_id: 'ch-zhongfu-02', knowledge_point_ids_json: '[]', front_content: '痛经的辨证要点和常见证型代表方？', back_content: '疼痛发生时间：经前痛=气滞或血瘀；经期痛=血瘀或寒凝；经后痛=气血虚或肾虚\n疼痛性质：胀痛=气滞；冷痛=寒凝；刺痛=血瘀；隐痛=虚证\n\n证型：\n1. 气滞血瘀证：膈下逐瘀汤（胀痛拒按+色暗有块）\n2. 寒凝血瘀证：少腹逐瘀汤（冷痛得热痛减）\n3. 湿热瘀阻证：清热调血汤（灼痛+经色深红质稠）\n4. 气血虚弱证：圣愈汤（隐痛喜按+经量少色淡）\n5. 肾气亏损证：调肝汤（腰膝酸软）', mnemonic: '时间→前气瘀期寒瘀后虚→证型→气寒湿热气血虚肾→五证', category: 'clinical', tags_json: '["月经病","痛经","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongfu3-103', subject_id: 'zhongfu', chapter_id: 'ch-zhongfu-04', knowledge_point_ids_json: '[]', front_content: '妊娠恶阻的辨证论治？', back_content: '恶阻=妊娠剧吐（妊娠早期恶心呕吐+头晕厌食）\n\n1. 脾胃虚弱证：妊娠早期恶心呕吐+吐出清涎+神疲思睡——香砂六君子汤\n2. 肝胃不和证：妊娠早期恶心呕吐+呕吐酸水或苦水+胁胀心烦——橘皮竹茹汤\n\n重证：\n呕吐剧烈不能进食+消瘦+尿少——需住院补液纠正电解质紊乱\n\n治疗原则："降逆止呕以安胎"、饮食宜清淡少食多餐。', mnemonic: '脾虚→香六和胃；肝胃→橘竹降逆→轻证用药重证补液', category: 'clinical', tags_json: '["妊娠病","恶阻","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongfu3-104', subject_id: 'zhongfu', chapter_id: 'ch-zhongfu-05', knowledge_point_ids_json: '[]', front_content: '产后病的病因病机特点和治疗原则？', back_content: '病因病机：\n1. 亡血伤津（产后失血多）\n2. 瘀血内阻（产后恶露未尽）\n3. 外感六淫或饮食劳倦\n4. "产后三病"——痉（抽搐）郁冒（眩晕）大便难\n\n治疗原则：\n1. "勿拘于产后亦勿忘于产后"（不能忽视产后特殊生理状况）\n2. 补虚不滞邪攻邪不伤正\n3. 常用生化汤加减（活血化瘀温经止痛——产后第一方）', mnemonic: '产后三因→亡血+瘀血+外感；三病→痉冒难；生化→产后第一方', category: 'clinical', tags_json: '["产后病","总论","高频"]', created_at: now, is_system: 1 },

    // ================================================================
    // 中医儿科学 (15 cards) — zhonger
    // ================================================================
    { id: 'fc-zhonger3-100', subject_id: 'zhonger', chapter_id: 'ch-zhonger-01', knowledge_point_ids_json: '[]', front_content: '小儿的生理病理特点是什么？', back_content: '生理特点：\n1. 脏腑娇嫩形气未充（"稚阴稚阳"——各系统发育不成熟）\n   - 尤其"肺常不足""脾常不足"（最薄弱环节）\n2. 生机蓬勃发育迅速（"纯阳之体"——生长速度快新陈代谢旺盛）\n\n病理特点：\n1. 发病容易传变迅速（"易虚易实易寒易热"）\n2. 脏气清灵易趋康复（治疗得当即恢复快）\n\n"儿科古称哑科"。', mnemonic: '生理→娇嫩+蓬勃；病理→易病易变+易复→稚阳+纯阳', category: 'definition', tags_json: '["总论","生理病理","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhonger3-101', subject_id: 'zhonger', chapter_id: 'ch-zhonger-03', knowledge_point_ids_json: '[]', front_content: '小儿腹泻的常见证型和代表方？', back_content: '常证：\n1. 伤食泻：大便稀溏夹有食物残渣气味酸腐——消乳丸（婴儿）/保和丸\n2. 风寒泻：大便清稀多泡沫+肠鸣腹痛——藿香正气散\n3. 湿热泻：大便水样色黄褐臭秽——葛根芩连汤\n4. 脾虚泻：大便稀溏食后即泻神疲乏力——参苓白术散\n5. 脾肾阳虚泻：久泻不止大便清稀完谷不化——附子理中汤合四神丸\n\n变证（危重）：\n气阴两伤：人参乌梅汤\n阴竭阳脱：生脉散合参附龙牡救逆汤', mnemonic: '食→保和；寒→藿香；热→葛芩；虚→参苓；久→附理合四→五常证', category: 'clinical', tags_json: '["脾胃病证","腹泻","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhonger3-102', subject_id: 'zhonger', chapter_id: 'ch-zhonger-03', knowledge_point_ids_json: '[]', front_content: '疳证的分型、临床表现和治疗原则？', back_content: '疳证=小儿营养不良。疳者干也（形容消瘦），疳者甘也（过食肥甘）。\n\n分型：\n疳气（初）：形体略消瘦面色萎黄食欲减退神疲——资生健脾丸\n疳积（中）：明显消瘦腹大脐突青筋暴露+烦躁——肥儿丸\n干疳（极）：极度消瘦皮肤干枯老人貌奄奄一息——八珍汤\n\n兼证：\n眼疳（角膜软化）心疳（口疮）疳肿胀（水肿）\n\n治疗原则：健脾益气消积导滞。', mnemonic: '疳→气→积→干：消瘦加重→资生→肥儿→八珍→三级递进', category: 'clinical', tags_json: '["脾胃病证","疳证","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhonger3-103', subject_id: 'zhonger', chapter_id: 'ch-zhonger-06', knowledge_point_ids_json: '[]', front_content: '小儿麻疹的临床表现和辨证论治？', back_content: '分期：\n前驱期（疹前期）：发热咳嗽流涕眼红流泪——宣毒发表汤\n出疹期：皮疹按顺序出现（耳后发际→面部→躯干→四肢）——清解透表汤\n恢复期（疹回期）：皮疹消退皮肤脱屑色素沉着——沙参麦冬汤\n\n逆证（危重）：\n麻毒闭肺（合并肺炎）：麻杏石甘汤\n热毒攻喉（喉炎）：清咽下痰汤\n邪陷心肝（脑炎）：羚角钩藤汤\n\n"麻为阳毒——麻不厌透"。', mnemonic: '顺证→前驱→出疹→恢复；逆证→闭肺攻喉陷肝→三逆变', category: 'clinical', tags_json: '["传染病","麻疹","高频"]', created_at: now, is_system: 1 },

    // ================================================================
    // 针灸学 (15 cards) — zhenjiu
    // ================================================================
    { id: 'fc-zhenjiu3-100', subject_id: 'zhenjiu', chapter_id: 'ch-zhenjiu-01', knowledge_point_ids_json: '[]', front_content: '十二经脉气血流注次序（十二经循环）？', back_content: '手太阴肺经→手阳明大肠经→足阳明胃经→足太阴脾经\n→手少阴心经→手太阳小肠经→足太阳膀胱经→足少阴肾经\n→手厥阴心包经→手少阳三焦经→足少阳胆经→足厥阴肝经\n→（复注于手太阴肺经）\n\n规律：阴阳表里经交替（肺大肠胃脾心小肠膀肾包三胆肝）\n每日一循环：始于寅时（3-5时肺经）终于丑时（1-3时肝经）。', mnemonic: '肺大肠胃脾心小肠，膀肾包三胆肝→再回肺→手足阴阳表里循环', category: 'definition', tags_json: '["经络","流注次序","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjiu3-101', subject_id: 'zhenjiu', chapter_id: 'ch-zhenjiu-02', knowledge_point_ids_json: '[]', front_content: '特定穴的分类及各自特点（十大特定穴）？', back_content: '1. 五输穴：井荥输经合（62穴，位于肘膝以下）\n2. 原穴：12个（脏腑原气所过之处）\n3. 络穴：15个（表里两经络脉相通之处）\n4. 郄穴：16个（气血深聚之处——主治急性病）\n5. 背俞穴：12个（脏腑之气输注背部）\n6. 募穴：12个（脏腑之气汇聚胸腹）\n7. 八会穴：8个（脏会腑会气会血会筋会脉会骨会髓会）\n8. 八脉交会穴：8个（与奇经八脉相通）\n9. 下合穴：6个（六腑之气合入下肢）\n10. 交会穴：多个（两条以上经脉交会之处）', mnemonic: '五输+原络+郄+背俞+募+八会+交会+下合→十类特定穴', category: 'definition', tags_json: '["腧穴","特定穴","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjiu3-102', subject_id: 'zhenjiu', chapter_id: 'ch-zhenjiu-06', knowledge_point_ids_json: '[]', front_content: '针刺异常情况的处理（晕针、滞针、弯针、断针）？', back_content: '晕针：立即起针去枕平卧饮温糖水重者按压人中→休克急救（患者紧张体质虚弱饥饿等易发）\n滞针：消除紧张情绪轻轻按摩针刺周围待肌肉放松后起针\n弯针：顺弯曲方向缓慢起针不强行拔出\n断针：浅部外露用镊子取出深部需X线定位手术取出\n\n防止：\n- 操作前全面评估\n- 空腹疲劳等暂不针刺\n- 严格消毒\n- 使用一次性合格针具', mnemonic: '晕→平卧；滞→放松；弯→顺拔；断→取→预防为先', category: 'clinical', tags_json: '["刺灸法","异常处理","高频"]', created_at: now, is_system: 1 },

    // ================================================================
    // 传染病学 (15 cards) — chuanran
    // ================================================================
    { id: 'fc-chuanran3-100', subject_id: 'chuanran', chapter_id: 'ch-chuanran-01', knowledge_point_ids_json: '[]', front_content: '传染病的基本特征和流行过程要素？', back_content: '基本特征：\n1. 有病原体（细菌病毒寄生虫等）\n2. 有传染性\n3. 有流行病学特征（流行性季节性地方性）\n4. 感染后获得免疫\n\n流行过程三大要素：\n1. 传染源（患者携带者受感染动物）\n2. 传播途径（呼吸道消化道血液体液虫媒等）\n3. 易感人群（缺乏特异性免疫力的人群）\n\n"控制任一环节即可阻断流行"。', mnemonic: '病原+传染+流行+免疫→四特征；源+途径+易感→三要素', category: 'definition', tags_json: '["传染病总论","基本概念","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-chuanran3-101', subject_id: 'chuanran', chapter_id: 'ch-chuanran-01', knowledge_point_ids_json: '[]', front_content: '传染病病程发展的四个阶段？', back_content: '1. 潜伏期：病原体侵入人体至出现症状前的时期\n2. 前驱期：出现特异症状之前的非特异性症状期（发热乏力不适）——诊断价值有限但已有传染性\n3. 症状明显期：具有该传染病特征性表现的阶段（最具诊断价值）\n4. 恢复期：症状逐渐消退组织修复——部分疾病可出现后遗症\n\n注意：某些传染病可不经历全部阶段（如暴发性肝炎）。', mnemonic: '潜伏→前驱→症状明显→恢复→四期递进→各具特点', category: 'definition', tags_json: '["传染病总论","病程"]', created_at: now, is_system: 1 },
  ]

  await knex('flashcards').insert(cards)
  const count = await knex('flashcards').count('* as c').first()
  console.log(`[Seed 012] ${cards.length}张记忆卡片已导入 (总计: ${(count as { c: number }).c})`)
}
