import { Knex } from 'knex'

export async function seed(knex: Knex): Promise<void> {
  const now = Date.now()
  const cards: Array<{
    id: string; subject_id: string; chapter_id: string; knowledge_point_ids_json: string
    front_content: string; back_content: string; mnemonic: string; category: string
    tags_json: string; created_at: number; is_system: number
  }> = [

    // ================================================================
    // 中医基础理论 (25 cards) — fc-zhongji-5001 ~ 5025
    // ================================================================
    { id: 'fc-zhongji-5001', subject_id: 'zhongji', chapter_id: 'ch-zhongji-01', knowledge_point_ids_json: '[]', front_content: '中医学的两个基本特点是什么？', back_content: '1. 整体观念——人体自身是有机整体、人与自然统一性\n2. 辨证论治——辨病与辨证相结合\n\n症（症状体征）、证（某阶段病理概括）、病（疾病的完整过程）三者的区别是辨证的核心。', mnemonic: '整体观=人自身+人与自然统一；辨证论治=同病异治+异病同治', category: 'definition', tags_json: '["总论","基本特点","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5002', subject_id: 'zhongji', chapter_id: 'ch-zhongji-01', knowledge_point_ids_json: '[]', front_content: '金元四大家各自的学派和核心观点？', back_content: '刘完素——寒凉派——"六气皆从火化"善用寒凉\n张从正——攻邪派——"邪去则正安"汗吐下法\n李杲——补土派——"内伤脾胃百病由生"补脾胃\n朱震亨——滋阴派——"阳常有余阴常不足"重滋阴\n\n简称：刘寒、张攻、李土、朱阴。', mnemonic: '刘寒张攻李补土，朱阴——简称记四人', category: 'definition', tags_json: '["总论","金元四大家","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5003', subject_id: 'zhongji', chapter_id: 'ch-zhongji-01', knowledge_point_ids_json: '[]', front_content: '四大经典的名称和主要贡献？', back_content: '1.《黄帝内经》——医家之宗——阴阳五行藏象经络奠基\n2.《难经》——独取寸口脉法、奇经八脉\n3.《伤寒杂病论》——辨证论治、"方书之祖"（张仲景"医圣"）\n4.《神农本草经》——首分上中下三品载药365种、四气五味\n\n补充：王叔和《脉经》、皇甫谧《针灸甲乙经》、巢元方《诸病源候论》也很重要。', mnemonic: '内奠理论、难创脉诊、伤立辨证、本载药物——四经奠基', category: 'definition', tags_json: '["总论","经典著作","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5004', subject_id: 'zhongji', chapter_id: 'ch-zhongji-02', knowledge_point_ids_json: '[]', front_content: '阴阳消长平衡"此消彼长"与"皆消皆长"的区别举例？', back_content: '此消彼长（对立双方一增一减）：\n- 阴消阳长：从冬到夏——寒气渐消热气渐增\n- 阳消阴长：从夏到冬——热气渐消寒气渐增\n\n皆消皆长（互根互用的消长）：\n- 阳生阴长：气旺→血充（共同增长）\n- 气虚→血少（共同减少）\n\n这是阴阳关系中消长平衡的两种形式，体现了阴阳既对立又统一的关系。', mnemonic: '此消彼长=对立制约；皆消皆长=互根互用——来源不同', category: 'definition', tags_json: '["阴阳学说","消长平衡","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5005', subject_id: 'zhongji', chapter_id: 'ch-zhongji-02', knowledge_point_ids_json: '[]', front_content: '阴阳对立制约"阴胜则阳病"与阴阳互根互用"阴损及阳"的病机有何不同？', back_content: '阴胜则阳病：阴邪偏盛损伤阳气（实证）\n- 病机：阴寒太盛→损耗阳气→局部寒实+整体阳受损\n- 如寒邪直中→既见恶寒肢冷（阴盛）又见腹痛（伤阳）\n\n阴损及阳：阴虚日久→阳气生化不足（虚证转两虚）\n- 病机：阴液亏虚→阳无所依→阳气亦渐衰弱\n- 如肝肾阴虚日久→阴虚阳亢→后期阴阳两虚\n\n关键区别：前者为实（邪盛），后者为虚（正亏）。', mnemonic: '胜=邪气盛（实），损=正气虚（虚）——虚实的本质区分', category: 'clinical', tags_json: '["阴阳学说","病机鉴别","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5006', subject_id: 'zhongji', chapter_id: 'ch-zhongji-03', knowledge_point_ids_json: '[]', front_content: '五行相生相克的完整次序及各自涉及的脏腑关系？', back_content: '相生：木→火→土→金→水→木\n- 水生木：肾水滋养肝木——"滋水涵木"\n- 木生火：肝藏血济心血——"木生火"\n- 火生土：心阳温运脾土——"益火补土"\n- 土生金：脾运精微养肺——"培土生金"\n- 金生水：肺气肃降水滋肾——"金水相生"\n\n相克：木→土→水→火→金→木\n- 木克土：肝气疏泄防脾壅滞——"抑木扶土"\n- 土克水：脾运水湿防肾水泛滥——"培土制水"', mnemonic: '生→木火土金水循环；克→间隔一个跳着克→木土水火金', category: 'definition', tags_json: '["五行学说","生克次序","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5007', subject_id: 'zhongji', chapter_id: 'ch-zhongji-03', knowledge_point_ids_json: '[]', front_content: '临床上根据五行相生相克确定的常用治法（8条）？', back_content: '根据相生（虚则补其母）：\n1.滋水涵木（养肾阴养肝阴）——杞菊地黄丸\n2.培土生金（补脾益肺）——参苓白术散\n3.益火补土（温心阳暖脾土）——附子理中汤\n4.金水相生（肺肾阴虚同治）——百合固金汤\n\n根据相克（抑强扶弱）：\n5.抑木扶土（疏肝健脾）——逍遥散/痛泻要方\n6.佐金平木（清肺泻肝）——黛蛤散合泻白散\n7.培土制水（健脾利水）——实脾饮\n8.泻南补北（泻心火滋肾水）——交泰丸', mnemonic: '四生法=滋培益金；四克法=抑佐培泻——每法配代表方', category: 'clinical', tags_json: '["五行学说","治法","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5008', subject_id: 'zhongji', chapter_id: 'ch-zhongji-04', knowledge_point_ids_json: '[]', front_content: '五脏与五体、五华、五官、五液、五志的对应关系全表？', back_content: '心：脉、面、舌、汗、喜\n肺：皮、毛、鼻、涕、悲（忧）\n脾：肉、唇、口、涎、思\n肝：筋、爪、目、泪、怒\n肾：骨、发、耳及二阴、唾、恐\n\n临床意义：\n- 肝血不足→爪甲不荣（其华在爪）\n- 肾精不足→发枯脱落（其华在发）\n- 心火上炎→口舌生疮（开窍于舌）', mnemonic: '心脉面舌汗喜，肺皮毛鼻涕悲，脾肉唇口涎思，肝筋爪目泪怒，肾骨发耳唾恐', category: 'definition', tags_json: '["藏象","五脏联属","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5009', subject_id: 'zhongji', chapter_id: 'ch-zhongji-04', knowledge_point_ids_json: '[]', front_content: '肺主通调水道和"肺为水之上源"的生理病理联系？', back_content: '生理：肺通过宣发和肃降调节水液代谢\n- 宣发——向上向外布散津液→体表、呼吸道（汗）\n- 肃降——向下向内输送水液→肾和膀胱（尿）\n\n"肺为水之上源"——肺居上焦统领水液代谢\n- 上源不通→下流不畅→小便不利水肿\n- 肺失宣降→水液停聚→痰饮水湿\n\n治疗：宣肺利水——越婢加术汤治风水（提壶揭盖法）——"开肺窍以通下焦"。', mnemonic: '肺→水上源→宣汗+降尿→失职则肿→越婢加术汤开上以通下', category: 'clinical', tags_json: '["藏象","肺","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5010', subject_id: 'zhongji', chapter_id: 'ch-zhongji-04', knowledge_point_ids_json: '[]', front_content: '脾主升清的两个含义及其病理表现？', back_content: '升清含义一：上输水谷精微于心肺头目\n- 病理：脾不升清→头目失养→眩晕耳鸣+清气下陷→泄泻\n\n升清含义二：升举内脏维持恒定位置\n- 病理：脾虚气陷→内脏下垂——脱肛、胃下垂、肾下垂、子宫脱垂\n- 代表方：补中益气汤升阳举陷\n\n"清气在下则生飧泄"——脾不升清→清气不升反降→泄泻。\n"浊气在上则生䐜胀"——胃不降浊→浊气在上→胀满。', mnemonic: '脾升清→上养头目+举内脏；下陷→头晕泻+内脏垂→补中益气', category: 'clinical', tags_json: '["藏象","脾","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5011', subject_id: 'zhongji', chapter_id: 'ch-zhongji-04', knowledge_point_ids_json: '[]', front_content: '肝主疏泄的具体生理作用有哪些？', back_content: '1. 调畅气机——全身气机调畅（最核心功能）\n   - 气机郁滞→情志抑郁、胸胁胀痛\n2. 促进脾胃运化——协调脾升胃降\n   - 肝气犯胃→恶心呕吐；肝气乘脾→腹痛泄泻\n3. 调畅情志——气机调畅则心情舒畅\n4. 促进血液与津液运行输布\n5. 调节生殖功能——调节冲任二脉\n\n肝失疏泄→气机郁滞→情志抑郁/气血津液运行障碍\n肝疏太过→肝气上逆→面红目赤头胀痛', mnemonic: '肝疏→气+食+情+血津+生殖→五方面疏泄功能', category: 'definition', tags_json: '["藏象","肝","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5012', subject_id: 'zhongji', chapter_id: 'ch-zhongji-04', knowledge_point_ids_json: '[]', front_content: '肾藏精的具体含义及"天癸"的概念？', back_content: '肾藏精包括：\n1. 先天之精——禀受父母（生命本原）\n2. 后天之精——水谷精微化生（充养先天）\n\n肾精的功能：\n- 主生长发育——"女子七岁肾气盛…二七天癸至…七七天癸竭"\n- 主生殖——肾精充盈产生天癸促进生殖功能成熟\n- 濡养脏腑——"肾为先天之本五脏之根"\n\n天癸：肾精充盈到一定程度产生的促进生殖功能的物质——女二七男二八天癸至——绝经/衰老标志。', mnemonic: '肾精→先天源头+后天补给→生长+生殖→天癸是关键', category: 'definition', tags_json: '["藏象","肾","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5013', subject_id: 'zhongji', chapter_id: 'ch-zhongji-05', knowledge_point_ids_json: '[]', front_content: '气与血的关系包括哪些方面？举例说明。', back_content: '1. 气能生血——气旺则血生化有源\n   例：气虚→血虚——八珍汤（四君补气+四物补血）\n\n2. 气能行血——气推动血液运行\n   例：气虚→血瘀——补阳还五汤（重用黄芪补气行血）\n\n3. 气能摄血——气统摄血液行于脉内\n   例：气不摄血→出血——归脾汤（补气摄血）\n\n4. 血能载气——气附于血中运行全身\n   例：大出血→气随血脱——独参汤（"有形之血不能速生，无形之气所当急固"）\n\n5. 血能生气——血为气的生成提供物质基础', mnemonic: '气→生血+行血+摄血；血→载气+生气——气血互生互用', category: 'definition', tags_json: '["气血津液","气血关系","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5014', subject_id: 'zhongji', chapter_id: 'ch-zhongji-05', knowledge_point_ids_json: '[]', front_content: '气机（气的运动）的基本形式和五脏气机特点？', back_content: '基本形式：升降出入——"升降出入无器不有"\n\n五脏气机特点：\n- 心：心火下行温肾水（宜降）\n- 肺：宣发（升）+肃降（降）——以降为主\n- 脾：主升清和升举（宜升）——"脾宜升则健"\n- 肝：主升主动（宜升）\n- 肾：肾水上济心阴（宜升）\n\n脾胃为气机升降之枢纽——脾升胃降协调全身气机\n脾胃升降失司→清阳不升+浊阴不降→百病由生', mnemonic: '心肺降+肝脾肾升+脾胃枢纽——升降协调=健康', category: 'definition', tags_json: '["气血津液","气机","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5015', subject_id: 'zhongji', chapter_id: 'ch-zhongji-06', knowledge_point_ids_json: '[]', front_content: '十二经脉走向规律及交接规律？', back_content: '走向规律：\n- 手三阴经：胸→手（从胸走手）\n- 手三阳经：手→头（从手走头）\n- 足三阳经：头→足（从头走足）\n- 足三阴经：足→腹/胸（从足走腹）\n\n交接规律：\n- 表里两经在手足末端交接（如肺经→食指末端→大肠经）\n- 同名阳经在头面部交接（手阳明→鼻旁→足阳明）\n- 手足阴经在胸腹部交接（足太阴→心中→手少阴）', mnemonic: '手三阴胸到手，手三阳手到头，足三阳头到足，足三阴足到腹', category: 'definition', tags_json: '["经络","十二经脉","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5016', subject_id: 'zhongji', chapter_id: 'ch-zhongji-06', knowledge_point_ids_json: '[]', front_content: '奇经八脉的名称和主要功能特点？', back_content: '八脉：任、督、冲、带、阴跷、阳跷、阴维、阳维\n\n核心三条：\n- 任脉——阴脉之海、主胞胎（调节阴经气血+孕育胎儿）\n- 督脉——阳脉之海（调节阳经气血）\n- 冲脉——十二经脉之海、血海（调节月经、女子以血为本）\n\n功能特点：\n1. 密切十二经脉联系——沟通调节气血\n2. 调节十二经脉气血——蓄积和渗灌气血\n3. 与肝、肾、脑、髓、女子胞等脏腑器官关系密切\n\n"冲为血海任主胞胎"——冲任不调为妇科病常见病机。', mnemonic: '奇经八脉→任阴督阳冲血→血海+胞胎+阳海→三条最核心', category: 'definition', tags_json: '["经络","奇经八脉","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5017', subject_id: 'zhongji', chapter_id: 'ch-zhongji-08', knowledge_point_ids_json: '[]', front_content: '风邪的致病特点及临床意义（善行、数变、百病之长）？', back_content: '善行——病位游走不定（行痹——关节痛游走各处）\n数变——发病急、变化快（风疹——出没无常、此起彼伏）\n主动——肢体动摇不定（破伤风→角弓反张；内风→抽搐）\n轻扬开泄——易袭阳位（头面+肌表）\n\n"风为百病之长"双重含义：\n1. 六淫中致病最广泛——风邪致病的范围和频率最高\n2. 常为外邪致病先导兼夹他邪——风寒、风热、风湿\n\n治疗："治风先治血血行风自灭"——活血可帮助祛风。', mnemonic: '风→善行（位不定）+数变（急变）+主动（肢摇）+外感先导', category: 'clinical', tags_json: '["病因","风邪","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5018', subject_id: 'zhongji', chapter_id: 'ch-zhongji-08', knowledge_point_ids_json: '[]', front_content: '湿邪致病"黏滞"的两层含义？为什么湿邪最难祛除？', back_content: '黏滞含义一（症状）：各种黏滞不爽的表现\n- 大便粘滞不爽——湿热泄泻\n- 小便涩滞——湿热淋浊\n- 分泌物混浊——带下黏稠\n\n黏滞含义二（病程）：起病缓慢、病程较长、迁延难愈\n- 湿温病——长期低热不退（"身热不扬"）\n- 湿疹——反复发作、缠绵难愈\n\n湿邪难祛除的原因：\n1. 湿为阴邪——黏腻重浊——如油入面难以速除\n2. 易伤脾阳——脾虚失运→湿愈重→恶性循环\n3. 易兼夹他邪——寒湿湿热互结更加难解', mnemonic: '黏滞→二含义：症状黏（便黏）+病程长（难愈）；治疗难→阴阳互结', category: 'clinical', tags_json: '["病因","湿邪","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5019', subject_id: 'zhongji', chapter_id: 'ch-zhongji-08', knowledge_point_ids_json: '[]', front_content: '瘀血致病的疼痛特征与其他类型疼痛的鉴别要点？', back_content: '疼痛性质鉴别表：\n- 瘀血——刺痛如针刺固定不移拒按夜甚\n- 气滞——胀痛走窜不定\n- 寒邪——冷痛得温痛减\n- 热邪——灼热痛（烧灼感）\n- 虚证——隐痛绵绵不休喜按\n- 湿邪——重痛（沉重感）\n- 痰饮——闷痛\n- 结石/虫积——绞痛（阵发性剧烈疼痛）\n- 食积——胀满痛\n\n瘀血疼痛综合特征：固定性+针刺感+夜间加重+拒按+舌紫暗脉涩。', mnemonic: '瘀→刺（针刺感）+固（位不移）+夜（夜重）+拒（拒按）+舌脉', category: 'clinical', tags_json: '["病因","瘀血","疼痛鉴别","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5020', subject_id: 'zhongji', chapter_id: 'ch-zhongji-09', knowledge_point_ids_json: '[]', front_content: '阴阳格拒（真寒假热/真热假寒）的病机和辨证关键？', back_content: '真寒假热（阴盛格阳——"至盛有虚象"）：\n- 病机：阴寒内盛太甚→虚阳被格拒于外\n- 假热象：面红如妆（仅在两颧）+烦躁（但精神萎靡）\n- 本质：渴不欲饮/欲热饮但不多饮+下肢厥冷\n- 舌脉：舌淡苔白、脉微细欲绝（真实）\n\n真热假寒（阳盛格阴——"至实有羸状"）：\n- 病机：阳热内盛太甚→阳气被郁→不能外达\n- 假寒象：四肢厥冷\n- 本质：胸腹灼热+不恶寒反恶热+烦渴喜冷饮\n- 舌脉：舌红绛苔黄燥、脉沉实有力（真实）\n\n辨证关键：舌质舌苔和脉象反映真实病性——不可被假象迷惑！', mnemonic: '真假鉴别看舌脉——舌淡白=真寒，舌红绛=真热——舌脉是根本', category: 'clinical', tags_json: '["病机","阴阳格拒","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5021', subject_id: 'zhongji', chapter_id: 'ch-zhongji-10', knowledge_point_ids_json: '[]', front_content: '"反治"四法各自的含义和临床应用举例？', back_content: '1. 热因热用——用热药治"假热"证\n   例：四逆汤治真寒假热（面红如妆）\n\n2. 寒因寒用——用寒药治"假寒"证\n   例：白虎汤治真热假寒（四肢厥冷）\n\n3. 塞因塞用——用补益药治"闭塞不通"证\n   例：补中益气汤治脾虚腹胀（胃下垂腹胀）\n\n4. 通因通用——用通利药治"通利太过"证\n   例：大承气汤治热结旁流（腹泻清水样便实为燥屎内结）\n\n核心原理：药性顺从疾病"假象"而实质与疾病"本质"相反——针对根本病机。', mnemonic: '反治四法→热用热、寒用寒、塞用补、通用通——治假求真', category: 'clinical', tags_json: '["防治原则","反治","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5022', subject_id: 'zhongji', chapter_id: 'ch-zhongji-10', knowledge_point_ids_json: '[]', front_content: '标本缓急三原则各自的适用时机和举例？', back_content: '1. 急则治其标——标证危及生命时先救标\n   例：大出血→先止血（治标）→再治病因（治本）\n   例：哮喘大发作→先平喘→再调体质\n   例：肠梗阻→先通腑→再治病因\n\n2. 缓则治其本——病情缓和时从根本治疗\n   例：阴虚咳嗽→滋阴润肺治阴虚之本\n   例：脾虚泄泻→健脾益气治脾虚之本\n\n3. 标本同治——本标同重时同时治疗\n   例：体虚感冒→益气解表（参苏饮——扶正+解表）\n   例：气虚血瘀中风→补阳还五汤（补气+活血）', mnemonic: '急→救命先治标（出血止血、喘憋平喘）；缓→病根治本；同治→扶正祛邪并用', category: 'clinical', tags_json: '["防治原则","标本缓急","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5023', subject_id: 'zhongji', chapter_id: 'ch-zhongji-02', knowledge_point_ids_json: '[]', front_content: '阴阳学说中"交感互藏"的生理意义是什么？', back_content: '交感：阴阳二气在运动中相互感应交合——万物化生的根本\n- 天地交感而生万物\n- 男女精气交感而生命延续\n\n互藏：阴中有阳、阳中有阴\n- 卦象体现：离卦（火）中虚（外阳内阴）、坎卦（水）中满（外阴内阳）\n- 人体：心属火（阳中寓阴）、肾属水（阴中含阳）\n\n互藏是消长转化的内在基础：\n- 阴中含阳→阴发展到极点可转化为阳\n- 阳中含阴→阳发展到极点可转化为阴\n\n"阴平阳秘精神乃治"——阴阳交感互藏维持生命的和谐统一。', mnemonic: '交感→和合交泰；互藏→你中有我；二者→阴阳转化的内在根基', category: 'definition', tags_json: '["阴阳学说","交感互藏"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5024', subject_id: 'zhongji', chapter_id: 'ch-zhongji-09', knowledge_point_ids_json: '[]', front_content: '"内生五邪"（内风、内寒、内湿、内燥、内火）的病因病机？', back_content: '内风——肝阳化风（眩晕肢麻）、热极生风（抽）、阴虚动风（蠕动）、血虚生风（肢麻）\n内寒——阳气不足温煦减弱（畏寒喜暖肢冷蜷缩脉迟）\n内湿——脾失健运水湿内停（脘痞呕恶腹胀便溏水肿）\n内燥——津液亏虚失于滋润（口干咽燥皮肤干燥便秘）\n内火——阳盛有余（实火）或阴虚阳亢（虚火）\n\n与外感六淫的区别：外感六淫由外而感发病急有表证；内生五邪由内生发无表证。', mnemonic: '内风→肝热阴虚血虚致动；内寒→阳虚不温；内湿→脾不运；内燥→津亏；内火→阳盛阴虚', category: 'clinical', tags_json: '["病机","内生五邪","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhongji-5025', subject_id: 'zhongji', chapter_id: 'ch-zhongji-10', knowledge_point_ids_json: '[]', front_content: '三因制宜（因时、因地、因人）的具体内容？', back_content: '1. 因时制宜：根据时令气候制定治则\n   - "用寒远寒"——寒冷季节慎用寒凉药\n   - "用热远热"——炎热季节慎用温热药\n   - 季节不同同一疾病治法不同\n\n2. 因地制宜：根据地理环境制定治则\n   - 西北高寒→多用温热药（"寒者热之"）\n   - 东南湿热→多用清利药（"湿者利之"）\n\n3. 因人制宜：根据年龄性别体质制定治则\n   - 小儿脏腑娇嫩→慎用峻剂\n   - 老人多虚→慎用攻伐\n   - 妇女经期孕期产后→治法不同\n   - 体质壮实耐攻→虚弱不耐攻', mnemonic: '三因→时（四季寒暑）、地（南北湿热寒）、人（老幼男女体质）', category: 'clinical', tags_json: '["防治原则","三因制宜"]', created_at: now, is_system: 1 },

    // ================================================================
    // 中医诊断学 (25 cards) — fc-zhenjuan-5001 ~ 5025
    // ================================================================
    { id: 'fc-zhenjuan-5001', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '望诊中得神、少神、失神、假神的主要鉴别特征？', back_content: '得神（有神）：目光明亮、面色荣润、神志清醒、气息均匀——正气未伤\n少神（神气不足）：精神不振、目光乏神、少气懒言——正气轻伤（虚证）\n失神（无神）：精神萎靡、目光晦暗、反应迟钝、郑声——正气大伤（危重）\n假神（回光返照）：久病重病突然红光满面精神转佳索食多语——残灯复明阴阳离决之危象（短期多死亡）\n\n重点：假神与得神的区别——"突然好转但整体衰竭仍在"——关键鉴别点。', mnemonic: '得→神旺；少→神衰；失→神散；假→暂好转但危绝——四神递进', category: 'definition', tags_json: '["望诊","望神","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5002', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '五色主病中青色和黑色的主病鉴别（容易混淆）？', back_content: '青色——寒证、痛证、气滞、血瘀、惊风（小儿）\n- 面色青——寒凝气滞脉络不通\n- 小儿眉间鼻柱唇周青色——惊风先兆\n\n黑色——肾虚、寒证、水饮、血瘀、剧痛\n- 面色黧黑晦暗——肾阳虚（重）\n- 面黑而干焦——肾精亏耗/肾阴虚（虚火灼）\n- 眼眶周围发黑——肾虚水饮/寒湿带下\n\n青色与黑色的共同主病：寒证、血瘀。\n青色从肝论、黑色从肾论——青偏于寒痛瘀，黑偏于肾虚水寒。', mnemonic: '青→寒痛瘀惊（偏肝）；黑→肾虚水寒瘀（偏肾）——二色偏重不同', category: 'definition', tags_json: '["望诊","五色","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5003', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '淡白舌、红舌、绛舌、青紫舌各自的主病及病机？', back_content: '淡白舌：主虚证（气虚血虚阳虚）和寒证\n- 病机：气血亏虚无以上荣舌面/阳虚寒凝\n  - 淡白而胖嫩边有齿痕=阳虚水湿\n  - 淡白而瘦薄=气血两虚\n\n红舌：主热证\n- 病机：热盛→气血涌盛于舌\n  - 鲜红干裂=实热（热盛伤津）\n  - 红而少苔或无苔=虚热（阴虚火旺）\n\n绛舌（深红）：热入营血（实）/阴虚火旺（虚）\n- 绛舌有苔→实热已入营分\n- 绛舌少苔或无苔→阴虚火旺（内伤）\n\n青紫舌：血瘀主舌', mnemonic: '淡白→虚寒；红→热；绛→热深入营；紫→血瘀——舌色由浅入深由表入里', category: 'definition', tags_json: '["舌诊","舌色","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5004', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '腻苔和腐苔的鉴别要点及各自的临床意义？', back_content: '腻苔：苔质颗粒细腻致密融合成片如油腻覆盖舌面\n- 刮之不去——湿浊内停（痰饮、食积）\n- 白腻=寒湿；黄腻=湿热\n\n腐苔：苔质颗粒粗大疏松如豆腐渣堆积舌面\n- 刮之易脱落——食积肠胃、痰浊\n- 多为阳热有余蒸腾腐浊之气上升\n\n鉴别口诀：\n- 腻苔——"如油似漆黏附难除"（细密湿浊）\n- 腐苔——"如腐似渣疏松易刮"（粗松食积）\n\n临床意义：腻多湿浊痰饮，腐多食积痰浊（实证为主）。', mnemonic: '腻→细密黏=湿浊；腐→粗松易刮=食积——质感之别', category: 'definition', tags_json: '["舌诊","苔质","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5005', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-02', knowledge_point_ids_json: '[]', front_content: '谵语与郑声的鉴别要点（考试绝对重点）？', back_content: '谵语——实热证：\n- 神识不清+语无伦次+声音高亢有力\n- 病机：热扰心神（阳明腑实/热入心包）\n- 方药：大承气汤/安宫牛黄丸\n\n郑声——虚寒证：\n- 神识不清+语言重复+声音低微无力\n- 病机：心气大伤精神散乱（正气欲脱）\n- 预后：多不良\n\n独语——自言自语喃喃不休见人则止——心气不足或痰蒙心窍（阴证）\n错语——言语错乱说后自知——心脾两虚（虚证）\n\n谵实郑虚——声高有力=谵证（实热），声低无力=郑声（虚脱）——这是最关键的鉴别点。', mnemonic: '谵→声高有力+乱语=实热；郑→声低无力+重复=虚脱——声力为鉴别关键', category: 'definition', tags_json: '["闻诊","语言","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5006', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-03', knowledge_point_ids_json: '[]', front_content: '潮热的三种类型及各自特征、病机、代表方？', back_content: '阳明潮热（日晡潮热）：\n- 时间：下午3-5时（申时）\n- 特征：热势较高、汗出热不退\n- 病机：阳明腑实证——大承气汤\n\n阴虚潮热（午后潮热）：\n- 时间：午后或入夜\n- 特征：低热不退+五心烦热+盗汗颧红\n- 病机：阴虚内热——清骨散/知柏地黄丸\n\n湿温潮热（身热不扬）：\n- 时间：午后热甚\n- 特征：初扪不热久扪灼手+头身困重\n- 病机：湿热内蕴——三仁汤', mnemonic: '阳明→申时高热（承气）；阴虚→午后低热（清骨）；湿温→午后身热不扬（三仁）', category: 'clinical', tags_json: '["问诊","潮热","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5007', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-03', knowledge_point_ids_json: '[]', front_content: '自汗与盗汗的病机和代表方？', back_content: '自汗——日间汗出活动后加重\n- 病机：气虚（卫外不固）或阳虚\n- 代表方：玉屏风散（气虚）\n- 伴随：神疲乏力、面色苍白、易感冒\n\n盗汗——入睡后汗出醒则汗止\n- 病机：阴虚内热（虚热迫津外泄）\n- 代表方：当归六黄汤（阴虚火旺）\n- 伴随：潮热、颧红、手足心热、舌红少苔\n\n大汗——大量汗出（里热蒸津或亡阳）\n战汗——先恶寒战栗后汗出（邪正交争关键时期）', mnemonic: '自汗→气虚固不住（白昼）——玉屏风；盗汗→阴虚关不住（入睡）——当归六黄', category: 'definition', tags_json: '["问诊","汗证","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5008', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-03', knowledge_point_ids_json: '[]', front_content: '十问歌的具体内容及含义？', back_content: '一问寒热二问汗——外感内伤鉴别\n三问头身四问便——躯体症状\n五问饮食六问胸——脏腑功能\n七聋八渴俱当辨——官窍诊断\n九问旧病十问因——病史和诱因\n再兼服药参机变——用药史\n妇人尤必问经期——妇科\n小儿当问斑疹疳——儿科\n\n临床必问内容：寒热（表里鉴别）、汗出（阴阳）、疼痛（部位性质）、饮食口味（脾胃）、二便（寒热虚实）、睡眠（心肾）、经带（妇科）。', mnemonic: '一问二问三四问→从头到脚问全+妇人经期+小儿斑疹→最全问诊', category: 'definition', tags_json: '["问诊","十问歌","基础"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5009', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-04', knowledge_point_ids_json: '[]', front_content: '28种脉象按分类如何记忆（六纲分类法）？', back_content: '脉位纲：浮（浮洪濡散芤革）、沉（沉伏牢弱）\n脉率纲：迟（迟缓涩结）、数（数促疾动）\n脉宽度纲：大（洪大实）、小（细小微）\n脉长度纲：长、短\n脉力度纲：虚（虚弱微）、实（实弦紧滑）\n脉紧张度纲：弦、紧、革、濡\n脉均匀度纲：结（缓而中止不规则）、代（止有定数）、促（数而中止不规则）\n\n六纲记忆法：浮沉迟数虚实滑弦——八个基本脉象为纲——其他28脉为目。', mnemonic: '六纲十字→浮沉迟数大小长→虚滑弦代→举一反三', category: 'definition', tags_json: '["脉诊","脉象分类","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5010', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-04', knowledge_point_ids_json: '[]', front_content: '浮脉类与沉脉类各自包含的脉象及主病？', back_content: '浮脉类（轻取即得）：\n- 浮脉→表证（有力=表实无力=表虚）\n- 洪脉→气分热盛（白虎汤证——四大症）\n- 濡脉→虚证湿证（浮细而软）\n- 散脉→元气离散（浮散无根）\n- 芤脉→大失血/伤阴（浮大中空如按葱管）\n- 革脉→亡血失精半产崩漏（浮而搏指外坚中空）\n\n沉脉类（重按始得）：\n- 沉脉→里证（有力=里实无力=里虚）\n- 伏脉→邪闭厥证痛极（重按推筋着骨始得）\n- 牢脉→阴寒内盛疝气癥瘕（沉而实大弦长有力）\n- 弱脉→气血两虚（沉细而软）', mnemonic: '浮类→浮+洪濡散芤革；沉类→沉+伏牢弱', category: 'definition', tags_json: '["脉诊","浮沉","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5011', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-06', knowledge_point_ids_json: '[]', front_content: '心系四证（心气虚、心阳虚、心血虚、心阴虚）的鉴别要点？', back_content: '共同心系症状：心悸怔忡、胸闷、不寐\n\n心气虚：心系基础症状+气短自汗+活动加重+舌淡脉弱\n心阳虚：心气虚症状+畏寒肢冷+心痛+舌淡胖脉迟紧\n心血虚：心系症状+面色萎黄+舌质淡白+脉细弱\n心阴虚：心系症状+潮热盗汗+五心烦热+舌红少苔+脉细数\n\n气虚vs阳虚→阳虚=气虚+寒象（畏寒肢冷）\n血虚vs阴虚→阴虚=血虚+虚热象（潮热盗汗）\n气虚→阳虚→亡阳（危证）；血虚→阴虚→亡阴（危证）。', mnemonic: '四证→共心症状+气/血/阳/阴各自特征→分虚寒(气阳)和虚热(血阴)两大类', category: 'clinical', tags_json: '["脏腑辨证","心病","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5012', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-06', knowledge_point_ids_json: '[]', front_content: '肝病四证（肝气郁结、肝火上炎、肝阳上亢、肝风内动）的鉴别与演变？', back_content: '肝气郁结（气滞）：\n- 特征：胸胁胀痛走窜+情志抑郁+脉弦\n- 病机：肝失疏泄气机郁滞→本证\n\n肝火上炎（实火）：郁久化火→\n- 特征：头痛眩晕+面红目赤口苦+舌红苔黄脉弦数\n- 病机：肝气郁滞化火上冲→实证\n\n肝阳上亢（阴虚阳亢）：肾阴虚→\n- 特征：上盛（眩晕头痛面赤脉弦）+下虚（腰膝酸软舌红少苔）\n- 病机：肝肾阴虚阴不制阳→本虚标实\n\n肝风内动（风动）：阳亢极化→\n- 特征：眩晕欲仆+肢麻震颤+言语不利\n- 病机：阳亢化风→风中脏腑/经络\n\n演变规律：郁→火→亢→风', mnemonic: '郁→火→亢→风进化：由气到血由实到虚由静到动', category: 'clinical', tags_json: '["脏腑辨证","肝病","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5013', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-06', knowledge_point_ids_json: '[]', front_content: '肾病五证的鉴别要点及代表方？', back_content: '肾阳虚证：腰膝冷痛+畏寒肢冷+小便清长或水肿+阳痿早泄\n    —金匮肾气丸/右归丸\n\n肾阴虚证：腰膝酸软+头晕耳鸣+潮热盗汗+遗精\n    —六味地黄丸/左归丸\n\n肾精不足证：小儿发育迟缓+成人早衰耳鸣发脱+生殖功能低下\n    —五子衍宗丸\n\n肾气不固证：小便频数清长遗尿+遗精滑精早泄\n    —金锁固精丸\n\n肾不纳气证：久病咳喘呼多吸少动则喘甚\n    —人参蛤蚧散/七味都气丸', mnemonic: '阳虚→寒；阴虚→热；精亏→衰；不固→漏；不纳→喘→五证各有主症', category: 'clinical', tags_json: '["脏腑辨证","肾病","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5014', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-06', knowledge_point_ids_json: '[]', front_content: '脾病各证（脾气虚、脾阳虚、脾虚气陷、脾不统血）的鉴别要点？', back_content: '四证均以脾气虚为基础（食少腹胀便溏乏力舌淡脉弱）\n\n脾气虚证：基础症状+面色萎黄\n— 代表方：四君子汤\n\n脾阳虚证：脾气虚+腹部冷痛喜温喜按+畏寒肢冷\n— 代表方：理中汤/附子理中汤\n\n脾虚气陷证：脾气虚+内脏下垂（脱肛胃下垂子宫脱垂）\n— 代表方：补中益气汤（升阳举陷）\n\n脾不统血证：脾气虚+出血（便血崩漏肌衄皮下瘀斑）\n— 代表方：归脾汤（补气摄血）\n\n演变：气虚→阳虚（加寒）、气虚→气陷（加陷）、气虚→不统血（加出血）。', mnemonic: '脾气虚为基→加寒=阳虚+加陷=气陷+加血=不统血→一基三变', category: 'clinical', tags_json: '["脏腑辨证","脾病","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5015', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-08', knowledge_point_ids_json: '[]', front_content: '六经辨证六经病的提纲证（必背条文）？', back_content: '太阳病："太阳之为病脉浮头项强痛而恶寒。"\n阳明病："阳明之为病胃家实是也。"\n少阳病："少阳之为病口苦咽干目眩也。"\n太阴病："太阴之为病腹满而吐食不下自利益甚时腹自痛。"\n少阴病："少阴之为病脉微细但欲寐也。"\n厥阴病："厥阴之为病消渴气上撞心心中疼热饥而不欲食。"\n\n临床意义：\n- 太阳病——表证（外感初期）\n- 阳明病——里实热证（高热便秘）\n- 少阳病——半表半里证（寒热往来）\n- 三阴病——里虚寒证（由轻到重）', mnemonic: '太阳头项强，阳明胃家实，少阳苦眩咽，太阴吐利满，少阴微细寐，厥阴消渴气撞', category: 'definition', tags_json: '["六经辨证","提纲证","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5016', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-08', knowledge_point_ids_json: '[]', front_content: '卫气营血辨证四阶段的治法要点？', back_content: '叶天士《温热论》原文：\n"在卫汗之可也"——辛凉解表（银翘散）\n"到气才可清气"——清热泻火（白虎汤）\n"入营犹可透热转气"——清营透热（清营汤）\n"入血就恐耗血动血直须凉血散血"——凉血散瘀（犀角地黄汤）\n\n各阶段临床表现：\n卫——发热微恶风寒+脉浮数\n气——壮热汗出口渴+脉洪大\n营——身热夜甚+斑疹隐隐+舌红绛\n血——各种出血+斑疹紫黑+舌深绛', mnemonic: '卫汗+气清+营透+血凉散——叶氏四句治则法门', category: 'clinical', tags_json: '["卫气营血","治则","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5017', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-05', knowledge_point_ids_json: '[]', front_content: '八纲辨证中虚实真假鉴别（"至虚有盛候"和"大实有羸状"）？', back_content: '真虚假实（至虚有盛候）：\n本质→正气大虚；表象→类似实证\n- 腹胀（假实）：虽腹胀但时减复如故、按之柔软喜按\n- 便秘（假实）：虽大便秘结但腹不胀满按之软\n字诀："虚证显现盛象"→用补法（塞因塞用）\n\n真实假虚（大实有羸状）：\n本质→邪气盛实；表象→类似虚证\n- 体倦乏力（假虚）：虽倦怠但语声有力且不久坐\n- 面色萎黄（假虚）：虽面色无华但有光泽\n字诀："实证呈现羸象"→用泻法（通因通用）\n\n鉴别核心：舌脉——舌质舌苔脉象反映真实病性。', mnemonic: '真假虚实望舌脉——实舌苍老苔厚脉有力→真虚；虚舌娇嫩苔少脉无力→真实', category: 'clinical', tags_json: '["八纲辨证","虚实","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5018', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '舌的动态（舌态）变化——强硬、痿软、歪斜、吐弄、短缩的临床意义？', back_content: '强硬舌：\n- 舌体板硬强直运转不灵——热入心包/高热伤津/中风\n\n痿软舌：\n- 舌体软弱无力不能随意伸缩——气血两虚/阴液极亏\n\n歪斜舌：\n- 伸舌时舌体偏向一侧——中风/中风先兆（中经络）\n\n颤动舌：\n- 伸舌时舌体不自主颤动——肝风内动\n   - 淡白颤动=血虚生风；红绛颤动=热极生风；少苔颤动=阴虚动风\n\n吐弄舌：\n- 舌伸口外不即回缩为吐舌——心脾有热\n- 舌微露出口即收或舔唇为弄舌——动风先兆/小儿智力发育不全\n\n短缩舌：舌体卷缩不能伸长——危重病证（寒/痰/热/虚四因均可致）。', mnemonic: '舌态→强硬=危中，歪斜=中风，颤动=动风，短缩=危重', category: 'clinical', tags_json: '["舌诊","舌态","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5019', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-03', knowledge_point_ids_json: '[]', front_content: '六经头痛的部位分属及机理？', back_content: '太阳头痛——后头部下连项背（后头痛）\n- 机理：太阳经循行后头→风寒束表→经脉不通\n\n阳明头痛——前额眉棱骨处（前头痛）\n- 机理：阳明经循行前额→胃热上扰\n\n少阳头痛——头两侧（偏头痛）\n- 机理：少阳经循行头侧→肝胆火旺\n\n厥阴头痛——巅顶部（头顶痛）\n- 机理：厥阴经上达巅顶→肝寒上逆/肝阳上亢\n\n少阴头痛——头痛连齿\n- 机理：少阴经循行齿根→肾虚头痛\n\n六经头痛为经络辨证在头痛定位中的具体运用——"头痛分经"指导针灸用药。', mnemonic: '太阳→后，阳明→前，少阳→侧，厥阴→顶，少阴→齿——六经六部位', category: 'clinical', tags_json: '["问诊","头痛","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5020', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-04', knowledge_point_ids_json: '[]', front_content: '脉诊中常见相兼脉象及其临床意义？', back_content: '浮紧脉→表寒证（外感风寒——麻黄汤）\n浮数脉→表热证（外感风热——银翘散）\n浮缓脉→表虚证（太阳中风——桂枝汤）\n沉迟脉→里寒证（阳虚寒盛）\n沉数脉→里热证\n沉细脉→里虚证（气血两虚/阴虚）\n弦数脉→肝火（肝火上炎/肝胆湿热）\n滑数脉→痰热/湿热/食积化热\n细数脉→阴虚内热\n弦滑脉→痰湿内阻+肝郁（多兼）\n\n相兼脉的分析原则：各个单一脉象主病的综合——如浮=表+紧=寒=表寒（风寒表证）。', mnemonic: '相兼脉=分别主病相加——浮紧=表+寒=风寒表证', category: 'definition', tags_json: '["脉诊","相兼脉","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5021', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-01', knowledge_point_ids_json: '[]', front_content: '黄疸之"阳黄"与"阴黄"的面色和病机区别？', back_content: '阳黄（湿热黄疸）：\n- 面色：黄色鲜明如橘皮色\n- 病机：湿热蕴蒸肝胆→胆汁外溢肌肤\n- 兼症：发热口渴小便黄舌红苔黄腻脉滑数\n- 治疗：茵陈蒿汤（清热利湿退黄）\n\n阴黄（寒湿黄疸）：\n- 面色：黄色晦暗如烟熏色\n- 病机：寒湿困脾→胆汁疏泄失常\n- 兼症：畏寒肢冷脘痞腹胀大便溏舌淡苔白腻脉沉迟\n- 治疗：茵陈术附汤（温化寒湿退黄）\n\n萎黄（非黄疸——注意鉴别）：\n- 面色萎黄无华——脾胃气虚/气血不足\n- 无巩膜黄染、小便不黄——茵陈剂无用', mnemonic: '阳黄→鲜如橘皮（湿热）；阴黄→暗如烟熏（寒湿）；萎黄→枯黄（气血虚）', category: 'clinical', tags_json: '["望诊","黄疸","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5022', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-07', knowledge_point_ids_json: '[]', front_content: '痰与饮的鉴别及中医四种饮证（痰饮、悬饮、支饮、溢饮）？', back_content: '鉴別：痰质稠浊流动性差；饮质清稀流动性大。\n\n四饮（张仲景《金匮要略》）：\n痰饮——饮停肠胃（脘腹痞胀水声漉漉）——苓桂术甘汤\n悬饮——饮停胸胁（胸胁胀满咳唾引痛）——十枣汤\n支饮——饮停胸膈（咳喘胸闷痰多清稀浮肿）——小青龙汤\n溢饮——饮溢四肢肌表（肢体浮肿沉重疼痛）——小青龙汤\n\n鉴别要点：停留部位不同→表现不同。\n共同病机：肺脾肾及三焦气化不利。', mnemonic: '痰→稠浊；饮→清稀；四饮→肠胃痰饮、胸胁悬饮、胸膈支饮、肌表溢饮', category: 'definition', tags_json: '["津液辨证","痰饮","高频"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5023', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-03', knowledge_point_ids_json: '[]', front_content: '问口渴的临床意义——口渴的多种表现形式分析？', back_content: '口不渴——津液未伤见于寒证或无明显热邪\n口渴欲饮——津液损伤或热盛（最常见）\n  大渴喜冷饮→实热证（阳明气分热盛——白虎汤证）\n  口渴喜热饮不多饮→虚寒证\n\n渴不多饮——津液输布障碍而非津液亏虚\n  渴不多饮+身热不扬→湿热内蕴（湿热困阻）\n  渴不多饮+舌红少苔→阴虚（虚火上扰但不至于大渴）\n  渴欲饮水水入即吐→水逆证（痰饮内停气化不利）\n\n此外：口干但欲漱水不欲咽→血瘀证（瘀血内阻津液不能上承）', mnemonic: '口不渴→津未伤或寒；大渴饮→热或伤津；渴不多饮→湿/瘀/阴虚；入水即吐→水逆', category: 'definition', tags_json: '["问诊","口渴","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5024', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-04', knowledge_point_ids_json: '[]', front_content: '小儿指纹（望小儿食指络脉）的临床诊断方法？', back_content: '适用年龄：3岁以内小儿\n\n观察部位：食指掌侧前缘络脉（虎口至指尖）\n分三关：风关（第一节）、气关（第二节）、命关（第三节）\n\n浮沉分表里：指纹浮显→表证；指纹沉隐→里证\n红紫辨寒热：鲜红→外感风寒；紫红→里热证；青色→惊风/痛证；淡白→脾虚疳积\n淡滞定虚实：色淡→虚证；色滞→实证（食积痰湿瘀阻）\n三关测轻重：指纹仅风关→轻症；达气关→重症；达命关→危重；透关射甲→病情极危', mnemonic: '浮沉表里+红紫寒热+淡滞虚实+三关轻重→四位一体诊断', category: 'definition', tags_json: '["望诊","小儿指纹","重点"]', created_at: now, is_system: 1 },
    { id: 'fc-zhenjuan-5025', subject_id: 'zhenjuan', chapter_id: 'ch-zhenjuan-05', knowledge_point_ids_json: '[]', front_content: '八纲辨证中"阴证"与"阳证"的范围和联系？', back_content: '阴证总括：里证、寒证、虚证——三者的共性是抑制、衰退、沉静\n- 临床表现：面色苍白或晦暗、声音低怯、少气懒言、畏寒肢冷\n\n阳证总括：表证、热证、实证——三者的共性是兴奋、亢进、躁动\n- 临床表现：面色红赤、声高气粗、烦躁多动、发热口渴\n\n阴阳为八纲总纲：\n- 表→阳、里→阴\n- 热→阳、寒→阴\n- 实→阳、虚→阴\n\n注意：临证时阴阳互有交错——表证可兼虚（表虚证）、里证可兼热（里热证）——不能机械划分。', mnemonic: '阴=里+寒+虚=抑制；阳=表+热+实=兴奋——八纲归阴阳', category: 'definition', tags_json: '["八纲辨证","阴阳","高频"]', created_at: now, is_system: 1 },
  ]

  // 批量插入（每批30条）
  for (let i = 0; i < cards.length; i += 30) {
    const batch = cards.slice(i, i + 30)
    await knex('flashcards').insert(batch)
  }
  console.log('[Seed 016] ' + cards.length + ' massive flashcards inserted')
}
