/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcupointIllustration: typeof import('./components/recite/AcupointIllustration.vue')['default']
    AppBreadcrumb: typeof import('./components/layout/AppBreadcrumb.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppMobileNav: typeof import('./components/layout/AppMobileNav.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    B1QuestionGroup: typeof import('./components/question/B1QuestionGroup.vue')['default']
    BookmarkButton: typeof import('./components/common/BookmarkButton.vue')['default']
    CompareTable: typeof import('./components/common/CompareTable.vue')['default']
    ContentContainer: typeof import('./components/layout/ContentContainer.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FlashCard: typeof import('./components/flashcard/FlashCard.vue')['default']
    FlashCardProgress: typeof import('./components/flashcard/FlashCardProgress.vue')['default']
    FlashCardRating: typeof import('./components/flashcard/FlashCardRating.vue')['default']
    PomodoroTimer: typeof import('./components/common/PomodoroTimer.vue')['default']
    QuestionCard: typeof import('./components/question/QuestionCard.vue')['default']
    QuestionFilter: typeof import('./components/question/QuestionFilter.vue')['default']
    QuestionNavigator: typeof import('./components/question/QuestionNavigator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./components/common/SearchPanel.vue')['default']
    TcmBadge: typeof import('./components/ui/TcmBadge.vue')['default']
    TcmButton: typeof import('./components/ui/TcmButton.vue')['default']
    TcmCard: typeof import('./components/ui/TcmCard.vue')['default']
    TcmDivider: typeof import('./components/ui/TcmDivider.vue')['default']
    TcmEmpty: typeof import('./components/ui/TcmEmpty.vue')['default']
    TcmProgress: typeof import('./components/ui/TcmProgress.vue')['default']
    TcmSkeleton: typeof import('./components/ui/TcmSkeleton.vue')['default']
    TcmTag: typeof import('./components/ui/TcmTag.vue')['default']
    TcmToast: typeof import('./components/ui/TcmToast.vue')['default']
  }
}
